; Generated by Sandbox LLVM backend
target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-i128:128-f80:128-n8:16:32:64-S128"
target triple = "x86_64-unknown-linux-gnu"

; External declarations
declare i64 @printf(i8*, ...)
declare i8* @malloc(i64)
declare void @free(i8*)
declare i32 @puts(i8*)
declare i32 @fputs(i8*, i8*)
declare i8* @strcat(i8*, i8*)
declare i64 @strlen(i8*)
declare i32 @strcmp(i8*, i8*)
declare i32 @snprintf(i8*, i64, i8*, ...)
declare i64 @strtol(i8*, i8**, i32)
declare double @strtod(i8*, i8**)

; Sandbox runtime helpers
declare i8* @sbx_rc_alloc(i64)
declare void @sbx_rc_retain(i8*)
declare i8* @__sbx_to_string(i64)
declare i8* @__sbx_to_string_f(double)
declare i8* @__sbx_str_concat_multi(i32, ...)
declare i64 @__sbx_future_spawn(i64)
declare i64 @__sbx_future_wait(i64)
declare i64 @__sbx_future_is_ready(i64)
declare void @__sbx_sleep(i64)
declare i64 @__sbx_time_ms()
declare i64 @__sbx_result_unwrap(i64)
declare i8* @__sbx_file_read(i8*)
declare void @__sbx_file_write(i8*, i8*)
declare i64 @__sbx_file_exists(i8*)
declare i8* @__sbx_str_sub(i8*, i64, i64)
declare i64 @__sbx_str_len(i8*)
declare i64 @__sbx_str_eq(i8*, i8*)
declare i8* @__sbx_str_concat(i8*, i8*)
declare i8* @__sbx_str_trim(i8*)
declare i64 @__sbx_str_starts_with(i8*, i8*)
declare i64 @__sbx_str_contains(i8*, i8*)
declare i64 @__sbx_str_find(i8*, i8*)
declare i8* @__sbx_str_to_upper(i8*)
declare i8* @__sbx_str_to_lower(i8*)
declare i8* @__sbx_str_replace(i8*, i8*, i8*)
declare void @__sbx_assert_eq(i64, i64)
declare void @__sbx_exit(i32)

@.str.0 = private constant [5 x i8] c"%ld\0A\00"

define void @main() {
entry:
  %v0 = alloca i64
  store i64 5, i64* %v0
  %v1 = load i64, i64* %v0
  %v2 = mul i64 %v1, 2
  call i64 (i8*, ...) @printf(i8* bitcast ([5 x i8]* @.str.0 to i8*), i64 %v2)
  ret void
}

