;; Generated by Sandbox v0.4.0
;; WebAssembly Text Format (.wat)

(module
  (import "console" "log" (func $log (param i64)))
  (memory (export "memory") 1)

  (func $main
    (local $temp i64)
    (local.set $temp
      (i64.const 5)
    )
    (call $log
      (i64.mul
        (local.get $x)
        (i64.const 2)
      )
    )
  )
  (export "main" (func $main))

)
