;; Generated by Sandbox v0.4.0
;; WebAssembly Text Format (.wat)

(module
  (import "console" "log" (func $log (param i64)))
  (memory (export "memory") 1)
  (data (i32.const 0)
    ("Hi")
  )

  (func $main
    (local $temp i64)
    (local.set $temp
      (i32.const 0)
    )
    (call $log
      (i64.const 0) ;; TODO: MethodCall { target: Ident("s"), method: "to_upper", args: [] }
    )
  )
  (export "main" (func $main))

)
