;; Generated by Sandbox v0.4.0
;; WebAssembly Text Format (.wat)

(module
  (import "console" "log" (func $log (param i64)))
  (memory (export "memory") 1)

  (func $main
    (local $temp i64)
    (local.set $temp
      (i64.const 0) ;; TODO: ArrayLiteral([Int(1), Int(2), Int(3)])
    )
    (local.set $temp
      (call $map
        (local.get $n)
        (i64.const 0) ;; TODO: Lambda { params: [Param { name: "x", ty: I64, default: None }], ret: None, body: [Return(Some(BinaryOp { op: Mul, left: Ident("x"), right: Int(2) }))] }
      )
    )
    (call $log
      (local.get $d)
    )
  )
  (export "main" (func $main))

)
