; Generated by Sandbox LLVM backend
target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-i128:128-f80:128-n8:16:32:64-S128"
target triple = "x86_64-unknown-linux-gnu"

; External declarations
declare i64 @printf(i8*, ...)
declare i8* @malloc(i64)
declare void @free(i8*)
declare i32 @puts(i8*)
declare i32 @fputs(i8*, i8*)
declare i8* @strcat(i8*, i8*)
declare i64 @strlen(i8*)
declare i32 @strcmp(i8*, i8*)
declare i32 @snprintf(i8*, i64, i8*, ...)
declare i64 @strtol(i8*, i8**, i32)
declare double @strtod(i8*, i8**)

; Sandbox runtime helpers
declare i8* @sbx_rc_alloc(i64)
declare void @sbx_rc_retain(i8*)
declare i8* @__sbx_to_string(i64)
declare i8* @__sbx_to_string_f(double)
declare i8* @__sbx_str_concat_multi(i32, ...)
declare i64 @__sbx_future_spawn(i64)
declare i64 @__sbx_future_wait(i64)
declare i64 @__sbx_future_is_ready(i64)
declare void @__sbx_sleep(i64)
declare i64 @__sbx_time_ms()
declare i64 @__sbx_result_unwrap(i64)
declare i8* @__sbx_file_read(i8*)
declare void @__sbx_file_write(i8*, i8*)
declare i64 @__sbx_file_exists(i8*)
declare i8* @__sbx_str_sub(i8*, i64, i64)
declare i64 @__sbx_str_len(i8*)
declare i64 @__sbx_str_eq(i8*, i8*)
declare i8* @sbx_map_new()
declare i64 @__sbx_map_insert(i8*, i8*, i64)
declare i64 @__sbx_map_get(i8*, i8*, i64)
declare i64 @__sbx_map_get_default(i8*, i8*, i64)
declare i64 @__sbx_map_has(i8*, i8*)
declare i64 @__sbx_map_remove(i8*, i8*)
declare i64 @__sbx_map_len(i8*)
declare i8* @__sbx_map_keys(i8*)
declare i8* @__sbx_map_format(i8*)
declare i64 @__sbx_json_array_get_int(i8*, i64)
declare i8* @__sbx_json_parse_map(i8*)
declare i8* @__sbx_json_stringify_map(i8*)
declare i8* @__sbx_json_get_str(i8*, i8*)
declare i64 @__sbx_json_get_int(i8*, i8*)
declare i8* @__sbx_json_stringify_array(i64, ...)
declare void @__sbx_serve(i64, i8* (i8*)*)
declare void @__sbx_serve_once(i64, i8* (i8*)*)
declare void @__sbx_http_serve_static(i8*)
declare i8* @__sbx_http_method()
declare i8* @__sbx_http_query()
declare i8* @__sbx_http_body()
declare i8* @__sbx_http_req_header(i8*)
declare void @__sbx_http_set_status(i64)
declare void @__sbx_http_set_header(i8*, i8*)
declare i64 @__sbx_http_status_code()
declare i8* @__sbx_http_query_param(i8*, i8*)
declare i8* @__sbx_http_form_get(i8*, i8*)
declare i8* @__sbx_http_form_param(i8*)
declare i8* @__sbx_url_decode(i8*)
declare void @__sbx_http_set_cookie(i8*, i8*)
declare i8* @__sbx_http_get_cookie(i8*)
declare i8* @__sbx_http_cookie_get(i8*, i8*)
declare i8* @__sbx_html_escape(i8*)
declare i8* @__sbx_html_unescape(i8*)
declare i8* @__sbx_tmpl_render(i64, ...)
declare i8* @__sbx_json_stringify(i64)
declare double @__sbx_json_stringify_float(double)
declare i8* @__sbx_json_get(i8*, i8*)
declare i8* @__sbx_json_stringify_string(i8*)
declare i8* @__sbx_json_stringify_bool(i64)
declare double @__sbx_json_parse_float(i8*)
declare i8* @__sbx_json_parse_string(i8*)
declare i64 @__sbx_json_has_key(i8*, i8*)
declare i64 @__sbx_json_array_len(i8*)
declare i8* @__sbx_json_parse_object(i8*)
declare i8* @__sbx_json_map_get(i8*, i8*)
declare i8* @__sbx_json_map_keys(i8*)
declare i64 @__sbx_json_map_len(i8*)
declare i8* @__sbx_str_concat(i8*, i8*)
declare i8* @__sbx_str_trim(i8*)
declare i64 @__sbx_str_starts_with(i8*, i8*)
declare i64 @__sbx_str_contains(i8*, i8*)
declare i64 @__sbx_str_find(i8*, i8*)
declare i8* @__sbx_str_to_upper(i8*)
declare i8* @__sbx_str_to_lower(i8*)
declare i8* @__sbx_str_replace(i8*, i8*, i8*)
declare void @__sbx_assert_eq(i64, i64)
declare void @__sbx_exit(i32)

@.str.0 = private constant [5 x i8] c"%ld\0A\00"
@.str.1 = private constant [5 x i8] c"%ld\0A\00"
@.str.2 = private constant [5 x i8] c"%ld\0A\00"
@.str.3 = private constant [4 x i8] c"%f\0A\00"

define void @sandbox_main() {
entry:
  %v0 = shl i64 4294967296, 56
  %v1 = lshr i64 %v0, 56
  %v2 = alloca i64
  store i64 %v1, i64* %v2
  %v3 = load i64, i64* %v2
  call i64 (i8*, ...) @printf(i8* bitcast ([5 x i8]* @.str.0 to i8*), i64 %v3)
  %v4 = shl i64 1, 56
  %v5 = lshr i64 %v4, 56
  %v6 = sub i64 0, %v5
  call i64 (i8*, ...) @printf(i8* bitcast ([5 x i8]* @.str.1 to i8*), i64 %v6)
  %v7 = fptosi double 2.9 to i64
  %v8 = shl i64 %v7, 56
  %v9 = lshr i64 %v8, 56
  call i64 (i8*, ...) @printf(i8* bitcast ([5 x i8]* @.str.2 to i8*), i64 %v9)
  %v10 = fptosi double 3.7 to i64
  call i64 (i8*, ...) @printf(i8* bitcast ([4 x i8]* @.str.3 to i8*), double %v10)
  ret void
}

define i32 @main() {
  call void @sandbox_main()
  ret i32 0
}

