;; Generated by Sandbox v0.4.0
;; WebAssembly Text Format (.wat)

(module
  (import "console" "log" (func $log (param i64)))
  (memory (export "memory") 1)

  (func $main
    (call $log
      (i64.add
        (i64.const 2)
        (i64.mul
          (i64.const 3)
          (i64.const 4)
        )
      )
    )
    (call $log
      (i64.sub
        (i64.sub
          (i64.const 10)
          (i64.const 4)
        )
        (i64.const 3)
      )
    )
    (call $log
      (i64.mul
        (i64.add
          (i64.const 2)
          (i64.const 3)
        )
        (i64.const 4)
      )
    )
    (call $log
      (i64.div_s
        (i64.const 17)
        (i64.const 5)
      )
    )
    (call $log
      (i64.rem_s
        (i64.const 17)
        (i64.const 5)
      )
    )
  )
  (export "main" (func $main))

)
