;; Generated by Sandbox v0.4.0
;; WebAssembly Text Format (.wat)

(module
  (import "console" "log" (func $log (param i64)))
  (memory (export "memory") 1)

  (func $main
    (local $a i64)
    (local $big i64)
    (local $u i64)
    (local.set $a
      (i64.shr_u
        (i64.shl
          (i64.const 4294967296)
          (i64.const 56)
        )
        (i64.const 56)
      )
    )
    (call $log
      (local.get $a)
    )
    (call $log
      (i64.shr_u
        (i64.shl
          (i64.sub
            (i64.const 0)
            (i64.const 1)
          )
          (i64.const 56)
        )
        (i64.const 56)
      )
    )
    (call $log
      (i64.shr_s
        (i64.shl
          (i64.sub
            (i64.const 0)
            (i64.const 1)
          )
          (i64.const 56)
        )
        (i64.const 56)
      )
    )
    (call $log
      (i64.shr_s
        (i64.shl
          (i64.const 255)
          (i64.const 56)
        )
        (i64.const 56)
      )
    )
    (call $log
      (i64.add
        (i64.shr_u
          (i64.shl
            (i64.const 200)
            (i64.const 56)
          )
          (i64.const 56)
        )
        (i64.shr_u
          (i64.shl
            (i64.const 100)
            (i64.const 56)
          )
          (i64.const 56)
        )
      )
    )
    (local.set $big
      (i64.shr_u
        (i64.shl
          (i64.const 456)
          (i64.const 56)
        )
        (i64.const 56)
      )
    )
    (call $log
      (local.get $big)
    )
    (call $log
      (local.get $big)
    )
    (call $log
      (i64.sub
        (i64.const 0)
        (i64.const 5)
      )
    )
    (call $log
      (i64.shr_u
        (i64.shl
          (i64.trunc_f64_s
            (f64.const 2.9)
          )
          (i64.const 56)
        )
        (i64.const 56)
      )
    )
    (call $log
      (i64.shr_u
        (i64.shl
          (i64.trunc_f64_s
            (f64.const -2.5)
          )
          (i64.const 56)
        )
        (i64.const 56)
      )
    )
    (call $log
      (i64.trunc_f64_s
        (f64.const 3.7)
      )
    )
    (local.set $u
      (i64.const 7)
    )
    (call $log
      (local.get $u)
    )
  )
  (export "main" (func $main))

)
