;; Generated by Sandbox v0.4.0
;; WebAssembly Text Format (.wat)

(module
  (import "console" "log" (func $log (param i64)))
  (memory (export "memory") 1)

  (func $clamp8 (param $x i64) (result i64)
        (i64.shr_s
      (i64.shl
        (i64.mul
          (local.get $x)
          (i64.const 1000)
        )
        (i64.const 48)
      )
      (i64.const 48)
    )
    (return)
  )

  (func $main
    (local $m i64)
    (local $s i64)
    (local $z i64)
    (call $log
      (call $clamp8
        (i64.const 100)
      )
    )
    (call $log
      (call $clamp8
        (i64.const 40)
      )
    )
    (local.set $m
      (i64.shr_u
        (i64.shl
          (i64.const 4000000000)
          (i64.const 32)
        )
        (i64.const 32)
      )
    )
    (local.set $m
      (i64.shr_u
        (i64.shl
          (i64.add
            (local.get $m)
            (i64.const 1000000000)
          )
          (i64.const 32)
        )
        (i64.const 32)
      )
    )
    (call $log
      (local.get $m)
    )
    (local.set $s
      (i64.shr_s
        (i64.shl
          (i64.const 100)
          (i64.const 56)
        )
        (i64.const 56)
      )
    )
    (local.set $s
      (i64.shr_s
        (i64.shl
          (i64.add
            (local.get $s)
            (i64.const 100)
          )
          (i64.const 56)
        )
        (i64.const 56)
      )
    )
    (call $log
      (local.get $s)
    )
    (local.set $z
      (i64.sub
        (i64.const 0)
        (i64.const 1)
      )
    )
    (call $log
      (local.get $z)
    )
  )
  (export "main" (func $main))

)
