;; Generated by Sandbox v0.4.0
;; WebAssembly Text Format (.wat)

(module
  (import "console" "log" (func $log (param i64)))
  (memory (export "memory") 1)

  (func $main
    (local $a i64)
    (local $b i64)
    (local.set $a
      (i64.const 12)
    )
    (local.set $b
      (i64.const 10)
    )
    (call $log
      (i64.and
        (local.get $a)
        (local.get $b)
      )
    )
    (call $log
      (i64.or
        (local.get $a)
        (local.get $b)
      )
    )
    (call $log
      (i64.xor
        (local.get $a)
        (local.get $b)
      )
    )
    (call $log
      (i64.xor
        (local.get $a)
        (i64.const -1)
      )
    )
    (call $log
      (i64.xor
        (i64.const 0)
        (i64.const -1)
      )
    )
    (call $log
      (i64.and
        (i64.const 255)
        (i64.const 15)
      )
    )
    (call $log
      (i64.xor
        (i64.sub
          (i64.const 0)
          (i64.const 1)
        )
        (i64.const 256)
      )
    )
  )
  (export "main" (func $main))

)
