;; Generated by Sandbox v0.4.0
;; WebAssembly Text Format (.wat)

(module
  (import "console" "log" (func $log (param i64)))
  (memory (export "memory") 1)

  (func $main
    (local $y i64)
    (local $y__s0 i64)
    (local.set $y
      (i64.const 5)
    )
    (if
      (i64.ne
        (i64.const 1)
        (i64.const 0)
      )
      (then
        (local.set $y__s0
          (i64.const 7)
        )
        (call $log
          (local.get $y__s0)
        )
      )
    )
    (call $log
      (local.get $y)
    )
  )
  (export "main" (func $main))

)
