;; Generated by Sandbox v0.4.0
;; WebAssembly Text Format (.wat)

(module
  (import "console" "log" (func $log (param i64)))
  (memory (export "memory") 1)

  (func $main
    (local $total i64)
    (local $bonus i64)
    (local $sum i64)
    (local $i i64)
    (local $step i64)
    (local.set $total
      (i64.const 0)
    )
    (if
      (i64.ne
        (i64.const 1)
        (i64.const 0)
      )
      (then
        (local.set $bonus
          (i64.const 40)
        )
        (local.set $total
          (i64.add
            (local.get $total)
            (local.get $bonus)
          )
        )
      )
    )
    (call $log
      (i64.add
        (local.get $total)
        (i64.const 2)
      )
    )
    (local.set $sum
      (i64.const 0)
    )
    (local.set $i
      (i64.const 0)
    )
    (block $break
      (loop $top
        (br_if $break
          (i32.eqz
            (i64.lt_s
              (local.get $i)
              (i64.const 3)
            )
          )
        )
        (block $continue
          (local.set $step
            (i64.mul
              (local.get $i)
              (i64.const 2)
            )
          )
          (local.set $sum
            (i64.add
              (local.get $sum)
              (local.get $step)
            )
          )
        )
        (local.set $i
          (i64.add
            (local.get $i)
            (i64.const 1)
          )
        )
        (br $top)
      )
    )
    (call $log
      (local.get $sum)
    )
  )
  (export "main" (func $main))

)
