;; Generated by Sandbox v0.4.0
;; WebAssembly Text Format (.wat)

(module
  (import "console" "log" (func $log (param i64)))
  (memory (export "memory") 1)

  (func $main
    (call $log
      (i64.const 1)
    )
    (call $log
      (i64.const 0)
    )
    (call $log
      (i64.lt_s
        (i64.const 1)
        (i64.const 2)
      )
      (i64.extend_i32_u)
    )
    (call $log
      (i64.eq
        (i64.const 2)
        (i64.const 2)
      )
      (i64.extend_i32_u)
    )
    (call $log
      (i64.ne
        (i64.const 3)
        (i64.const 3)
      )
      (i64.extend_i32_u)
    )
    (call $log
      (i64.and
        (i64.lt_s
          (i64.const 1)
          (i64.const 2)
        )
        (i64.extend_i32_u)
        (i64.lt_s
          (i64.const 2)
          (i64.const 3)
        )
        (i64.extend_i32_u)
      )
    )
    (call $log
      (i64.or
        (i64.const 0)
        (i64.const 1)
      )
    )
    (call $log
      (i64.extend_i32_u
        (i64.eqz
          (i64.const 0)
        )
      )
    )
  )
  (export "main" (func $main))

)
