;; Generated by Sandbox v0.4.0
;; WebAssembly Text Format (.wat)

(module
  (import "console" "log" (func $log (param i64)))
  (memory (export "memory") 1)

  (func $main
    (local $c i64)
    (local $r i64)
    (local.set $c
      (i64.const 0) ;; TODO: EnumVariant { enum_name: "Color", type_args: [], variant: "Green", payload: None }
    )
    (local.set $r
      (i64.const 0) ;; TODO: Match { scrutinee: Ident("c"), arms: [MatchArm { pattern: EnumVariant { enum_name: "Color", variant: "Red", binding: None }, guard: None, body: [ExprStmt(Int(1))] }, MatchArm { pattern: EnumVariant { enum_name: "Color", variant: "Green", binding: None }, guard: None, body: [ExprStmt(Int(2))] }, MatchArm { pattern: Wildcard, guard: None, body: [ExprStmt(Int(3))] }] }
    )
    (call $log
      (local.get $r)
    )
  )
  (export "main" (func $main))

)
