;; Generated by Sandbox v0.4.0
;; WebAssembly Text Format (.wat)

(module
  (import "console" "log" (func $log (param i64)))
  (memory (export "memory") 1)

  (func $main
    (local $m i64)
    (local $r i64)
    (local.set $m
      (i64.const 0) ;; TODO: EnumVariant { enum_name: "Maybe", type_args: [], variant: "Has", payload: Some(Int(42)) }
    )
    (local.set $r
      (i64.const 0) ;; TODO: Match { scrutinee: Ident("m"), arms: [MatchArm { pattern: EnumVariant { enum_name: "Maybe", variant: "Has", binding: Some("v") }, guard: None, body: [ExprStmt(Ident("v"))] }, MatchArm { pattern: Wildcard, guard: None, body: [ExprStmt(Int(0))] }] }
    )
    (call $log
      (local.get $r)
    )
  )
  (export "main" (func $main))

)
