;; Generated by Sandbox v0.4.0
;; WebAssembly Text Format (.wat)

(module
  (import "console" "log" (func $log (param i64)))
  (memory (export "memory") 1)

  (func $double (param $x i64) (result i64)
        (i64.mul
      (local.get $x)
      (i64.const 2)
    )
    (return)
  )

  (func $main
    (call $log
      (call $double
        (i64.const 21)
      )
    )
    (call $log
      (call $double
        (call $double
          (i64.const 3)
        )
      )
    )
  )
  (export "main" (func $main))

)
