;; Generated by Sandbox v0.4.0
;; WebAssembly Text Format (.wat)

(module
  (import "console" "log" (func $log (param i64)))
  (memory (export "memory") 1)

  (func $main
    (local $nums i64)
    (local $n i64)
    (local.set $nums
      (i64.const 0) ;; TODO: ArrayLiteral([Int(10), Int(20), Int(30)])
    )
  )
  (export "main" (func $main))

)
