;; Generated by Sandbox v0.4.0
;; WebAssembly Text Format (.wat)

(module
  (import "console" "log" (func $log (param i64)))
  (memory (export "memory") 1)

  (func $main
    (local $item i64)
  )
  (export "main" (func $main))

)
