;; Generated by Sandbox v0.4.0
;; WebAssembly Text Format (.wat)

(module
  (import "console" "log" (func $log (param i64)))
  (memory (export "memory") 1)

  (func $main
    (local $x i64)
    (local.set $x
      (i64.const 5)
    )
    (call $log
      (i64.const 0) ;; TODO: FString([Literal("x = "), Expr(Ident("x"))])
    )
    (call $log
      (i64.const 0) ;; TODO: FString([Expr(Ident("x")), Literal(" * "), Expr(Ident("x")), Literal(" = "), Expr(BinaryOp { op: Mul, left: Ident("x"), right: Ident("x") })])
    )
  )
  (export "main" (func $main))

)
