;; Generated by Sandbox v0.4.0
;; WebAssembly Text Format (.wat)

(module
  (import "console" "log" (func $log (param i64)))
  (memory (export "memory") 1)

  (func $main
    (local $p i64)
    (local.set $p
      (i64.const 0) ;; TODO: StructLiteral { name: "Pair", type_args: [I64], fields: [("first", Int(1)), ("second", Int(2))] }
    )
    (call $log
      (i64.add
        (i64.const 0) ;; TODO: FieldAccess { target: Ident("p"), field: "first" }
        (i64.const 0) ;; TODO: FieldAccess { target: Ident("p"), field: "second" }
      )
    )
  )
  (export "main" (func $main))

)
