;; Generated by Sandbox v0.4.0
;; WebAssembly Text Format (.wat)

(module
  (import "console" "log" (func $log (param i64)))
  (memory (export "memory") 1)

  (func $main
    (local $x i64)
    (local.set $x
      (i64.const 5)
    )
    (if
      (i64.gt_s
        (local.get $x)
        (i64.const 3)
      )
      (then
        (call $log
          (i64.const 1)
        )
      )
      (else
        (call $log
          (i64.const 0)
        )
      )
    )
    (if
      (i64.lt_s
        (local.get $x)
        (i64.const 0)
      )
      (then
        (call $log
          (i64.sub
            (i64.const 0)
            (i64.const 1)
          )
        )
      )
      (else
        (if
          (i64.eq
            (local.get $x)
            (i64.const 0)
          )
          (then
            (call $log
              (i64.const 0)
            )
          )
          (else
            (call $log
              (i64.const 2)
            )
          )
        )
      )
    )
  )
  (export "main" (func $main))

)
