;; Generated by Sandbox v0.4.0
;; WebAssembly Text Format (.wat)

(module
  (import "console" "log" (func $log (param i64)))
  (memory (export "memory") 1)

  (func $main
    (local $x i64)
    (local $r i64)
    (local.set $x
      (i64.const 5)
    )
    (local.set $r
      (i64.const 0) ;; TODO: Match { scrutinee: Ident("x"), arms: [MatchArm { pattern: IntLiteral(5), guard: None, body: [ExprStmt(Int(42))] }, MatchArm { pattern: Wildcard, guard: None, body: [ExprStmt(Int(0))] }] }
    )
    (call $log
      (local.get $r)
    )
  )
  (export "main" (func $main))

)
