;; Generated by Sandbox v0.4.0
;; WebAssembly Text Format (.wat)

(module
  (import "console" "log" (func $log (param i64)))
  (memory (export "memory") 1)

  (func $classify (param $n i64) (result i64)
        (i64.const 0) ;; TODO: Match { scrutinee: Ident("n"), arms: [MatchArm { pattern: Variable("x"), guard: Some(BinaryOp { op: Lt, left: Ident("x"), right: Int(0) }), body: [ExprStmt(Int(0))] }, MatchArm { pattern: Variable("x"), guard: Some(BinaryOp { op: Eq, left: Ident("x"), right: Int(0) }), body: [ExprStmt(Int(1))] }, MatchArm { pattern: Wildcard, guard: None, body: [ExprStmt(Int(2))] }] }
    (return)
  )

  (func $main
    (call $log
      (call $classify
        (i64.sub
          (i64.const 0)
          (i64.const 3)
        )
      )
    )
    (call $log
      (call $classify
        (i64.const 0)
      )
    )
    (call $log
      (call $classify
        (i64.const 7)
      )
    )
  )
  (export "main" (func $main))

)
