;; Generated by Sandbox v0.4.0
;; WebAssembly Text Format (.wat)

(module
  (import "console" "log" (func $log (param i64)))
  (memory (export "memory") 1)

  (func $main
    (local $price i64)
    (local.set $price
      (i64.const 105000)
    )
    (call $log
      (local.get $price)
    )
  )
  (export "main" (func $main))

)
