;; Generated by Sandbox v0.4.0
;; WebAssembly Text Format (.wat)

(module
  (import "console" "log" (func $log (param i64)))
  (memory (export "memory") 1)

  (func $main
    (local $a i64)
    (local $b i64)
    (local.set $a
      (i64.const 105000)
    )
    (local.set $b
      (i64.const 22500)
    )
    (call $log
      (i64.add
        (local.get $a)
        (local.get $b)
      )
    )
    (call $log
      (i64.mul
        (local.get $a)
        (i64.const 3)
      )
    )
  )
  (export "main" (func $main))

)
