;; Generated by Sandbox v0.4.0
;; WebAssembly Text Format (.wat)

(module
  (import "console" "log" (func $log (param i64)))
  (memory (export "memory") 1)

  (func $fact (param $n i64) (result i64)
    (if
      (i64.le_s
        (local.get $n)
        (i64.const 1)
      )
      (then
                (i64.const 1)
        (return)
      )
      (else
                (i64.mul
          (local.get $n)
          (call $fact
            (i64.sub
              (local.get $n)
              (i64.const 1)
            )
          )
        )
        (return)
      )
    )
    (unreachable)
  )

  (func $fib (param $n i64) (result i64)
    (if
      (i64.lt_s
        (local.get $n)
        (i64.const 2)
      )
      (then
                (local.get $n)
        (return)
      )
      (else
                (i64.add
          (call $fib
            (i64.sub
              (local.get $n)
              (i64.const 1)
            )
          )
          (call $fib
            (i64.sub
              (local.get $n)
              (i64.const 2)
            )
          )
        )
        (return)
      )
    )
    (unreachable)
  )

  (func $main
    (call $log
      (call $fact
        (i64.const 10)
      )
    )
    (call $log
      (call $fib
        (i64.const 15)
      )
    )
  )
  (export "main" (func $main))

)
