;; Generated by Sandbox v0.4.0
;; WebAssembly Text Format (.wat)

(module
  (import "console" "log" (func $log (param i64)))
  (memory (export "memory") 1)

  (func $main
    (call $log
      (i64.shl
        (i64.const 1)
        (i64.const 10)
      )
    )
    (call $log
      (i64.shr_s
        (i64.sub
          (i64.const 0)
          (i64.const 16)
        )
        (i64.const 2)
      )
    )
    (call $log
      (i64.shl
        (i64.add
          (i64.const 2)
          (i64.const 3)
        )
        (i64.mul
          (i64.const 1)
          (i64.const 2)
        )
      )
    )
    (call $log
      (i64.shl
        (i64.const 1)
        (i64.add
          (i64.const 3)
          (i64.const 1)
        )
      )
    )
    (call $log
      (i64.shr_s
        (i64.const 16)
        (i64.add
          (i64.const 1)
          (i64.const 1)
        )
      )
    )
    (call $log
      (i64.shr_s
        (call $a_shift_helper
          (i64.const 1)
          (i64.const 63)
        )
        (i64.const 62)
      )
    )
  )
  (export "main" (func $main))

  (func $a_shift_helper (param $v i64) (param $n i64) (result i64)
        (i64.shl
      (local.get $v)
      (local.get $n)
    )
    (return)
  )

)
