;; Generated by Sandbox v0.4.0
;; WebAssembly Text Format (.wat)

(module
  (import "console" "log" (func $log (param i64)))
  (memory (export "memory") 1)

  (func $main
    (local $p i64)
    (local.set $p
      (i64.const 0) ;; TODO: StructLiteral { name: "Point", type_args: [], fields: [("x", Int(3)), ("y", Int(4))] }
    )
    (call $log
      (i64.add
        (i64.const 0) ;; TODO: FieldAccess { target: Ident("p"), field: "x" }
        (i64.const 0) ;; TODO: FieldAccess { target: Ident("p"), field: "y" }
      )
    )
  )
  (export "main" (func $main))

)
