;; Generated by Sandbox v0.4.0
;; WebAssembly Text Format (.wat)

(module
  (import "console" "log" (func $log (param i64)))
  (memory (export "memory") 1)
  (global $heap (mut i32) (i32.const 0))
  (func $sbx_alloc (param $n i32) (result i32)
    (local $old i32)
    (local.set $old (global.get $heap))
    (global.set $heap (i32.add (global.get $heap) (local.get $n)))
    (return (local.get $old))
  )
  (func $sbx_arr_new (param $count i64) (result i64)
    (local $arr i32)
    (local.set $arr (call $sbx_alloc (i32.add (i32.const 8) (i32.wrap_i64 (i64.mul (local.get $count) (i64.const 8))))))
    (i64.store (local.get $arr) (local.get $count))
    (return (i64.extend_i32_u (local.get $arr)))
  )
  (func $sbx_len (param $arr i64) (result i64)
    (return (i64.load (i32.wrap_i64 (local.get $arr))))
  )
  (func $sbx_get (param $arr i64) (param $idx i64) (result i64)
    (return (i64.load (i32.add (i32.wrap_i64 (local.get $arr)) (i32.wrap_i64 (i64.add (i64.mul (local.get $idx) (i64.const 8)) (i64.const 8))))))
  )
  (func $sbx_store (param $arr i64) (param $idx i64) (param $v i64)
    (i64.store (i32.add (i32.wrap_i64 (local.get $arr)) (i32.wrap_i64 (i64.add (i64.mul (local.get $idx) (i64.const 8)) (i64.const 8)))) (local.get $v))
  )


  (func $main
    (local $a i64)
    (local.set $a
      (call $sbx_arr_new (i64.const 3))
    )
    (call $sbx_store (local.get $a) (i64.const 0) 
    (i64.const 10)
    )

    (call $sbx_store (local.get $a) (i64.const 1) 
    (i64.const 20)
    )

    (call $sbx_store (local.get $a) (i64.const 2) 
    (i64.const 30)
    )

    (call $log
      (call $sbx_get (local.get $a) 
      (i64.const 0)
      )
    )
    (call $log
      (call $sbx_get (local.get $a) 
      (i64.const 1)
      )
    )
    (call $log
      (call $sbx_get (local.get $a) 
      (i64.const 2)
      )
    )
    (call $log
      (call $sbx_len (local.get $a))
    )
  )
  (export "main" (func $main))

)
