;; Generated by Sandbox v0.4.0
;; WebAssembly Text Format (.wat)

(module
  (import "console" "log" (func $log (param i64)))
  (memory (export "memory") 1)

  (func $main
    (local $i i64)
    (local.set $i
      (i64.const 0)
    )
    (block $break
      (loop $continue
        (br_if $break
          (i32.eqz
            (i64.lt_s
              (local.get $i)
              (i64.const 3)
            )
          )
        )
        (call $log
          (local.get $i)
        )
        (local.set $i
          (i64.add
            (local.get $i)
            (i64.const 1)
          )
        )
        (br $continue)
      )
    )
  )
  (export "main" (func $main))

)
