#!/usr/bin/env bash
# Regenerate index.md (the GitHub Pages home page) from README.md.
#
# Why this exists: the Pages site is served from the repo root on master.
# With no index file, jekyll-readme-index injects README.md into the theme
# RAW — markdown inside <div align="center"> never converts and the closing
# </div> gets HTML-escaped, so the whole page renders as plain text.
# index.md fixes it: YAML front matter routes it through kramdown, and the
# markdown="1" attribute makes kramdown process the hero/footer divs
# (GitHub strips that attribute silently, so README.md stays unchanged).
#
# Re-run after every README change and commit both files together:
#
#   bash scripts/sync-pages.sh
set -euo pipefail
cd "$(dirname "$0")/.."

{
  cat <<'FM'
---
# Generated by scripts/sync-pages.sh — edit README.md, then re-run this.
layout: default
title: "🏖️ Sandbox"
---
FM
  # Drop the README's own H1 (the theme header carries the title) and mark
  # the centering divs so kramdown converts markdown inside them.
  sed -e '/^# 🏖️ Sandbox$/d' \
      -e 's/^<div align="center">$/<div align="center" markdown="1">/' \
      README.md
} > index.md

echo "index.md regenerated from README.md ($(wc -l < index.md) lines)"
