use crate::ast::*;
use std::collections::HashMap;
use std::fmt::Write;

/// LLVM IR text code generator.
/// Produces `.ll` files that can be compiled with `clang` or `llc`.
pub struct LlvmGen {
    output: String,
    strings: Vec<(String, String)>,
    var_counter: usize,
    fn_sigs: HashMap<String, (Vec<String>, String)>,
    enum_tags: HashMap<String, Vec<(String, i64)>>,
    struct_defs: HashMap<String, Vec<(String, String)>>,
    current_fn: String,
    variables: HashMap<String, (String, String)>,
    block_terminated: bool,
    lambda_counter: usize,
    #[allow(clippy::type_complexity)]
    pending_lambdas: Vec<(String, Vec<Param>, Option<Type>, Vec<Stmt>)>,
}

/// Check if an LLVM type string represents a named struct (e.g., "%Point")
fn is_struct_type(ty: &str) -> bool {
    ty.starts_with('%') && ty.len() > 1 && ty[1..].chars().all(|c| c.is_alphanumeric() || c == '_')
}

impl LlvmGen {
    pub fn new() -> Self {
        Self {
            output: String::new(),
            strings: Vec::new(),
            var_counter: 0,
            fn_sigs: HashMap::new(),
            enum_tags: HashMap::new(),
            struct_defs: HashMap::new(),
            current_fn: String::new(),
            variables: HashMap::new(),
            block_terminated: false,
            lambda_counter: 0,
            pending_lambdas: Vec::new(),
        }
    }

    pub fn generate(&mut self, program: &Program) -> String {
        // Register enum tags
        for item in &program.items {
            if let TopLevel::EnumDef { name, variants } = item {
                let tags: Vec<(String, i64)> = variants
                    .iter()
                    .enumerate()
                    .map(|(i, v)| (v.name.clone(), i as i64))
                    .collect();
                self.enum_tags.insert(name.clone(), tags);
            }
        }

        // Register struct definitions
        for item in &program.items {
            if let TopLevel::StructDef { name, fields } = item {
                let field_tys: Vec<(String, String)> = fields
                    .iter()
                    .map(|f| (f.name.clone(), self.llvm_type(&f.ty)))
                    .collect();
                self.struct_defs.insert(name.clone(), field_tys);
            }
        }

        // Register function signatures
        for item in &program.items {
            if let TopLevel::FnDef {
                name, params, ret, ..
            } = item
            {
                let param_tys: Vec<String> = params.iter().map(|p| self.llvm_type(&p.ty)).collect();
                let ret_ty = ret
                    .as_ref()
                    .map_or("void".to_string(), |t| self.llvm_type(t));
                self.fn_sigs.insert(name.clone(), (param_tys, ret_ty));
            }
        }

        // Preamble
        writeln!(self.output, "; Generated by Sandbox LLVM backend").unwrap();
        writeln!(self.output, "target datalayout = \"e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-i128:128-f80:128-n8:16:32:64-S128\"").unwrap();
        writeln!(self.output, "target triple = \"x86_64-unknown-linux-gnu\"").unwrap();
        writeln!(self.output).unwrap();

        // Declare external functions
        writeln!(self.output, "; External declarations").unwrap();
        writeln!(self.output, "declare i64 @printf(i8*, ...)").unwrap();
        writeln!(self.output, "declare i8* @malloc(i64)").unwrap();
        writeln!(self.output, "declare void @free(i8*)").unwrap();
        writeln!(self.output).unwrap();

        // Generate struct type definitions
        for (name, fields) in &self.struct_defs {
            let field_tys: Vec<String> = fields.iter().map(|(_, ty)| ty.clone()).collect();
            writeln!(
                self.output,
                "%{} = type {{ {} }}",
                name,
                field_tys.join(", ")
            )
            .unwrap();
        }
        if !self.struct_defs.is_empty() {
            writeln!(self.output).unwrap();
        }

        // Generate functions
        for item in &program.items {
            match item {
                TopLevel::FnDef {
                    name,
                    params,
                    ret,
                    body,
                } => {
                    self.gen_fn(name, params, ret, body);
                }
                TopLevel::EnumDef { name, variants } => {
                    self.gen_enum(name, variants);
                }
                _ => {}
            }
        }

        // Emit pending lambda definitions
        let lambdas: Vec<_> = self.pending_lambdas.clone();
        for (name, params, ret, body) in &lambdas {
            self.gen_fn(name, params, ret, body);
        }

        // String constants
        let mut string_section = String::new();
        for (name, content) in &self.strings {
            let mut byte_str = String::new();
            for b in content.bytes() {
                if (32..127).contains(&b) && b != b'"' {
                    byte_str.push(b as char);
                } else {
                    write!(&mut byte_str, "\\{:02X}", b).unwrap();
                }
            }
            writeln!(
                string_section,
                "@{} = private constant [{} x i8] c\"{}\\00\"",
                name,
                content.len() + 1,
                byte_str
            )
            .unwrap();
        }

        // Combine: preamble first, then string constants, then functions
        let preamble_end = self
            .output
            .find("; enum ")
            .or_else(|| self.output.find("define "))
            .unwrap_or(self.output.len());
        let mut result = String::new();
        result.push_str(&self.output[..preamble_end]);
        result.push_str(&string_section);
        result.push('\n');
        result.push_str(&self.output[preamble_end..]);
        result
    }

    fn gen_fn(&mut self, name: &str, params: &[Param], _ret: &Option<Type>, body: &[Stmt]) {
        self.current_fn = name.to_string();
        self.variables.clear();
        self.block_terminated = false;
        let (param_tys, ret_ty) = self.fn_sigs.get(name).cloned().unwrap_or_default();

        let params_str: Vec<String> = params
            .iter()
            .zip(&param_tys)
            .map(|(p, ty)| format!("{} %{}", ty, p.name))
            .collect();
        writeln!(
            self.output,
            "define {} @{}({}) {{",
            ret_ty,
            name,
            params_str.join(", ")
        )
        .unwrap();
        writeln!(self.output, "entry:").unwrap();

        // Allocate and store parameters
        for (i, p) in params.iter().enumerate() {
            let ty = &param_tys[i];
            let alloca = self.fresh_var();
            writeln!(self.output, "  {} = alloca {}", alloca, ty).unwrap();
            writeln!(
                self.output,
                "  store {} %{}, {}* {}",
                ty, p.name, ty, alloca
            )
            .unwrap();
            self.variables.insert(p.name.clone(), (alloca, ty.clone()));
        }

        // Generate body
        let mut last_val = "void".to_string();
        for stmt in body {
            last_val = self.gen_stmt(stmt);
        }

        // Return only if the current block isn't already terminated
        if !self.block_terminated {
            if ret_ty == "void" {
                writeln!(self.output, "  ret void").unwrap();
            } else if name == "main" {
                writeln!(self.output, "  ret {} 0", ret_ty).unwrap();
            } else {
                writeln!(self.output, "  ret {} {}", ret_ty, last_val).unwrap();
            }
        }

        writeln!(self.output, "}}").unwrap();
        writeln!(self.output).unwrap();
    }

    fn gen_enum(&mut self, name: &str, variants: &[EnumVariantDef]) {
        for (i, v) in variants.iter().enumerate() {
            let tag_name = format!("{}.{}", name, v.name);
            writeln!(self.output, "; enum {}::{} = {}", name, v.name, i).unwrap();
            writeln!(self.output, "@.tag.{} = constant i64 {}", tag_name, i).unwrap();
        }
        writeln!(self.output).unwrap();
    }

    fn gen_stmt(&mut self, stmt: &Stmt) -> String {
        match stmt {
            Stmt::Let {
                name, ty, value, ..
            } => {
                let llvm_ty = ty
                    .as_ref()
                    .map_or_else(|| self.infer_llvm_type(value), |t| self.llvm_type(t));
                if is_struct_type(&llvm_ty) {
                    // For struct types, StructLiteral already allocs + stores fields.
                    // Just alias the variable name to the same alloca.
                    let val = self.gen_expr(value);
                    self.variables.insert(name.clone(), (val.clone(), llvm_ty));
                    val
                } else {
                    let val = self.gen_expr(value);
                    let alloca = self.fresh_var();
                    writeln!(self.output, "  {} = alloca {}", alloca, llvm_ty).unwrap();
                    writeln!(
                        self.output,
                        "  store {} {}, {}* {}",
                        llvm_ty, val, llvm_ty, alloca
                    )
                    .unwrap();
                    self.variables.insert(name.clone(), (alloca, llvm_ty));
                    val
                }
            }
            Stmt::Assign { name, value } => {
                let val = self.gen_expr(value);
                if let Some((alloca, ty)) = self.variables.get(name) {
                    let alloca = alloca.clone();
                    let ty = ty.clone();
                    writeln!(self.output, "  store {} {}, {}* {}", ty, val, ty, alloca).unwrap();
                }
                val
            }
            Stmt::If {
                condition,
                then,
                else_,
            } => {
                let cond_val = self.gen_expr(condition);
                let then_label = self.fresh_label("if.then");
                let else_label = self.fresh_label("if.else");
                let end_label = self.fresh_label("if.end");

                writeln!(
                    self.output,
                    "  br i1 {}, label %{}, label %{}",
                    cond_val, then_label, else_label
                )
                .unwrap();
                self.block_terminated = true;

                writeln!(self.output, "{}:", then_label).unwrap();
                self.block_terminated = false;
                for s in then {
                    self.gen_stmt(s);
                }
                if !self.block_terminated {
                    writeln!(self.output, "  br label %{}", end_label).unwrap();
                    self.block_terminated = true;
                }

                writeln!(self.output, "{}:", else_label).unwrap();
                self.block_terminated = false;
                if let Some(else_body) = else_ {
                    for s in else_body {
                        self.gen_stmt(s);
                    }
                }
                if !self.block_terminated {
                    writeln!(self.output, "  br label %{}", end_label).unwrap();
                    self.block_terminated = true;
                }

                if self.block_terminated {
                    return "void".to_string();
                }
                writeln!(self.output, "{}:", end_label).unwrap();
                self.block_terminated = false;
                "void".to_string()
            }
            Stmt::While { condition, body } => {
                let cond_label = self.fresh_label("while.cond");
                let body_label = self.fresh_label("while.body");
                let end_label = self.fresh_label("while.end");

                writeln!(self.output, "  br label %{}", cond_label).unwrap();
                self.block_terminated = true;
                writeln!(self.output, "{}:", cond_label).unwrap();
                let cond_val = self.gen_expr(condition);
                writeln!(
                    self.output,
                    "  br i1 {}, label %{}, label %{}",
                    cond_val, body_label, end_label
                )
                .unwrap();
                self.block_terminated = true;

                writeln!(self.output, "{}:", body_label).unwrap();
                self.block_terminated = false;
                for s in body {
                    self.gen_stmt(s);
                }
                if !self.block_terminated {
                    writeln!(self.output, "  br label %{}", cond_label).unwrap();
                    self.block_terminated = true;
                }

                writeln!(self.output, "{}:", end_label).unwrap();
                self.block_terminated = false;
                "void".to_string()
            }
            Stmt::Return(Some(expr)) => {
                let val = self.gen_expr(expr);
                let ty = self.infer_llvm_type(expr);
                writeln!(self.output, "  ret {} {}", ty, val).unwrap();
                self.block_terminated = true;
                val
            }
            Stmt::Return(None) => {
                writeln!(self.output, "  ret void").unwrap();
                self.block_terminated = true;
                "void".to_string()
            }
            Stmt::Print(expr) => {
                let val = self.gen_expr(expr);
                let ty = self.infer_llvm_type(expr);
                self.gen_print_call(&val, &ty);
                "void".to_string()
            }
            Stmt::ExprStmt(expr) => self.gen_expr(expr),
            Stmt::For {
                variable,
                iterable,
                body,
            } => {
                if let Expr::Range {
                    start,
                    end,
                    inclusive,
                } = iterable
                {
                    let start_val = self.gen_expr(start);
                    let end_val = self.gen_expr(end);
                    let loop_var = variable.clone();
                    let cond_label = self.fresh_label("for.cond");
                    let body_label = self.fresh_label("for.body");
                    let end_label = self.fresh_label("for.end");
                    let incr_label = self.fresh_label("for.incr");

                    // Allocate loop variable
                    let alloca = self.fresh_var();
                    writeln!(self.output, "  {} = alloca i64", alloca).unwrap();
                    writeln!(self.output, "  store i64 {}, i64* {}", start_val, alloca).unwrap();
                    self.variables
                        .insert(loop_var.clone(), (alloca.clone(), "i64".to_string()));

                    // Branch to condition
                    writeln!(self.output, "  br label %{}", cond_label).unwrap();
                    self.block_terminated = true;

                    // Condition block
                    writeln!(self.output, "{}:", cond_label).unwrap();
                    self.block_terminated = false;
                    let loaded = self.fresh_var();
                    writeln!(self.output, "  {} = load i64, i64* {}", loaded, alloca).unwrap();
                    let cmp = self.fresh_var();
                    if *inclusive {
                        writeln!(
                            self.output,
                            "  {} = icmp sle i64 {}, {}",
                            cmp, loaded, end_val
                        )
                        .unwrap();
                    } else {
                        writeln!(
                            self.output,
                            "  {} = icmp slt i64 {}, {}",
                            cmp, loaded, end_val
                        )
                        .unwrap();
                    }
                    writeln!(
                        self.output,
                        "  br i1 {}, label %{}, label %{}",
                        cmp, body_label, end_label
                    )
                    .unwrap();
                    self.block_terminated = true;

                    // Body block
                    writeln!(self.output, "{}:", body_label).unwrap();
                    self.block_terminated = false;
                    for s in body {
                        self.gen_stmt(s);
                    }
                    if !self.block_terminated {
                        writeln!(self.output, "  br label %{}", incr_label).unwrap();
                        self.block_terminated = true;
                    }

                    // Increment block
                    writeln!(self.output, "{}:", incr_label).unwrap();
                    self.block_terminated = false;
                    let loaded2 = self.fresh_var();
                    writeln!(self.output, "  {} = load i64, i64* {}", loaded2, alloca).unwrap();
                    let incr = self.fresh_var();
                    writeln!(self.output, "  {} = add i64 {}, 1", incr, loaded2).unwrap();
                    writeln!(self.output, "  store i64 {}, i64* {}", incr, alloca).unwrap();
                    writeln!(self.output, "  br label %{}", cond_label).unwrap();
                    self.block_terminated = true;

                    // End block
                    writeln!(self.output, "{}:", end_label).unwrap();
                    self.block_terminated = false;
                    "void".to_string()
                } else {
                    for s in body {
                        self.gen_stmt(s);
                    }
                    "void".to_string()
                }
            }
        }
    }

    fn gen_expr(&mut self, expr: &Expr) -> String {
        match expr {
            Expr::Int(n) => format!("{}", n),
            Expr::Float(n) => format!("{}", n),
            Expr::Bool(b) => {
                if *b {
                    "1".to_string()
                } else {
                    "0".to_string()
                }
            }
            Expr::Str(s) => {
                let name = self.fresh_str(s);
                let len = s.len() + 1;
                format!("bitcast ([{} x i8]* @{} to i8*)", len, name)
            }
            Expr::Ident(name) => {
                if let Some((alloca, ty)) = self.variables.get(name) {
                    let alloca = alloca.clone();
                    let ty = ty.clone();
                    if is_struct_type(&ty) {
                        // For structs, return the alloca pointer (don't load the whole struct)
                        alloca
                    } else {
                        let loaded = self.fresh_var();
                        writeln!(
                            self.output,
                            "  {} = load {}, {}* {}",
                            loaded, ty, ty, alloca
                        )
                        .unwrap();
                        loaded
                    }
                } else {
                    format!("%{}", name)
                }
            }
            Expr::BinaryOp { op, left, right } => {
                let l = self.gen_expr(left);
                let r = self.gen_expr(right);
                let lt = self.infer_llvm_type(left);
                match op {
                    BinOp::Add => {
                        let result = self.fresh_var();
                        writeln!(self.output, "  {} = add {} {}, {}", result, lt, l, r).unwrap();
                        result
                    }
                    BinOp::Sub => {
                        let result = self.fresh_var();
                        writeln!(self.output, "  {} = sub {} {}, {}", result, lt, l, r).unwrap();
                        result
                    }
                    BinOp::Mul => {
                        let result = self.fresh_var();
                        writeln!(self.output, "  {} = mul {} {}, {}", result, lt, l, r).unwrap();
                        result
                    }
                    BinOp::Div => {
                        let result = self.fresh_var();
                        writeln!(self.output, "  {} = sdiv {} {}, {}", result, lt, l, r).unwrap();
                        result
                    }
                    BinOp::Eq => {
                        let result = self.fresh_var();
                        writeln!(self.output, "  {} = icmp eq {} {}, {}", result, lt, l, r)
                            .unwrap();
                        result
                    }
                    BinOp::Neq => {
                        let result = self.fresh_var();
                        writeln!(self.output, "  {} = icmp ne {} {}, {}", result, lt, l, r)
                            .unwrap();
                        result
                    }
                    BinOp::Lt => {
                        let result = self.fresh_var();
                        writeln!(self.output, "  {} = icmp slt {} {}, {}", result, lt, l, r)
                            .unwrap();
                        result
                    }
                    BinOp::Gt => {
                        let result = self.fresh_var();
                        writeln!(self.output, "  {} = icmp sgt {} {}, {}", result, lt, l, r)
                            .unwrap();
                        result
                    }
                    _ => format!("; unsupported op: {:?}", op),
                }
            }
            Expr::UnaryOp { op, expr } => {
                let val = self.gen_expr(expr);
                let ty = self.infer_llvm_type(expr);
                match op {
                    UnOp::Neg => {
                        let result = self.fresh_var();
                        writeln!(self.output, "  {} = sub {} 0, {}", result, ty, val).unwrap();
                        result
                    }
                    UnOp::Not => {
                        let result = self.fresh_var();
                        writeln!(self.output, "  {} = xor i1 {}, 1", result, val).unwrap();
                        result
                    }
                }
            }
            Expr::Call { name, args } => {
                let (param_tys, ret_ty) = self.fn_sigs.get(name).cloned().unwrap_or_else(|| {
                    let arg_tys: Vec<String> =
                        args.iter().map(|a| self.infer_llvm_type(a)).collect();
                    (arg_tys, "i64".to_string())
                });
                // Generate arg values, loading struct types from their allocas
                let mut arg_vals = Vec::new();
                for (i, a) in args.iter().enumerate() {
                    let val = self.gen_expr(a);
                    let ty = if i < param_tys.len() {
                        &param_tys[i]
                    } else {
                        &"i64".to_string()
                    };
                    if is_struct_type(ty) && is_struct_type(&self.infer_llvm_type(a)) {
                        // val is an alloca pointer but we need the struct value — load it
                        let loaded = self.fresh_var();
                        writeln!(self.output, "  {} = load {}, {}* {}", loaded, ty, ty, val)
                            .unwrap();
                        arg_vals.push(loaded);
                    } else {
                        arg_vals.push(val);
                    }
                }
                if ret_ty == "void" {
                    let args_str: Vec<String> = param_tys
                        .iter()
                        .zip(&arg_vals)
                        .map(|(ty, val)| format!("{} {}", ty, val))
                        .collect();
                    writeln!(
                        self.output,
                        "  call void @{}({})",
                        name,
                        args_str.join(", ")
                    )
                    .unwrap();
                    "void".to_string()
                } else {
                    let result = self.fresh_var();
                    let args_str: Vec<String> = param_tys
                        .iter()
                        .zip(&arg_vals)
                        .map(|(ty, val)| format!("{} {}", ty, val))
                        .collect();
                    writeln!(
                        self.output,
                        "  {} = call {} @{}({})",
                        result,
                        ret_ty,
                        name,
                        args_str.join(", ")
                    )
                    .unwrap();
                    result
                }
            }
            Expr::EnumVariant {
                enum_name, variant, ..
            } => {
                if let Some(tags) = self.enum_tags.get(enum_name) {
                    if let Some((_, tag)) = tags.iter().find(|(v, _)| v == variant) {
                        return format!("{}", tag);
                    }
                }
                "0".to_string()
            }
            Expr::Match { scrutinee, arms } => {
                let sc = self.gen_expr(scrutinee);
                let end_label = self.fresh_label("match.end");
                let result = self.fresh_var();
                writeln!(self.output, "  {} = alloca i64", result).unwrap();
                writeln!(self.output, "  store i64 0, i64* {}", result).unwrap();

                let num_arms = arms.len();
                let skip_labels: Vec<String> =
                    (0..num_arms).map(|_| self.fresh_label("skip")).collect();

                // Terminate the current basic block by branching to the first skip label
                writeln!(self.output, "  br label %{}", skip_labels[0]).unwrap();
                self.block_terminated = true;

                for (i, arm) in arms.iter().enumerate() {
                    writeln!(self.output, "{}:", skip_labels[i]).unwrap();
                    self.block_terminated = false;

                    let arm_label = self.fresh_label("match.arm");
                    let cond = match &arm.pattern {
                        Pattern::EnumVariant {
                            enum_name, variant, ..
                        } => {
                            let tag_val = self.enum_tags.get(enum_name).and_then(|tags| {
                                tags.iter().find(|(v, _)| v == variant).map(|(_, t)| *t)
                            });
                            if let Some(tag) = tag_val {
                                let cmp = self.fresh_var();
                                writeln!(self.output, "  {} = icmp eq i64 {}, {}", cmp, sc, tag)
                                    .unwrap();
                                cmp
                            } else {
                                "true".to_string()
                            }
                        }
                        Pattern::IntLiteral(n) => {
                            let cmp = self.fresh_var();
                            writeln!(self.output, "  {} = icmp eq i64 {}, {}", cmp, sc, n).unwrap();
                            cmp
                        }
                        _ => "true".to_string(),
                    };
                    let next_label = if i + 1 < num_arms {
                        &skip_labels[i + 1]
                    } else {
                        &end_label
                    };
                    writeln!(
                        self.output,
                        "  br i1 {}, label %{}, label %{}",
                        cond, arm_label, next_label
                    )
                    .unwrap();
                    self.block_terminated = true;
                    writeln!(self.output, "{}:", arm_label).unwrap();
                    self.block_terminated = false;
                    if let Some(last) = arm.body.last() {
                        let val = match last {
                            Stmt::ExprStmt(e) => self.gen_expr(e),
                            _ => "0".to_string(),
                        };
                        writeln!(self.output, "  store i64 {}, i64* {}", val, result).unwrap();
                    }
                    writeln!(self.output, "  br label %{}", end_label).unwrap();
                    self.block_terminated = true;
                }

                writeln!(self.output, "{}:", end_label).unwrap();
                self.block_terminated = false;
                let loaded = self.fresh_var();
                writeln!(self.output, "  {} = load i64, i64* {}", loaded, result).unwrap();
                loaded
            }
            Expr::StructLiteral { name, fields } => {
                let struct_ty = format!("%{}", name);
                let alloca = self.fresh_var();
                writeln!(self.output, "  {} = alloca {}", alloca, struct_ty).unwrap();
                let field_defs = self.struct_defs.get(name).cloned().unwrap_or_default();
                for (i, (_fname, field_val)) in fields.iter().enumerate() {
                    let val = self.gen_expr(field_val);
                    let field_ty = if i < field_defs.len() {
                        field_defs[i].1.clone()
                    } else {
                        "i64".to_string()
                    };
                    let gep = self.fresh_var();
                    writeln!(
                        self.output,
                        "  {} = getelementptr {}, {}* {}, i32 0, i32 {}",
                        gep, struct_ty, struct_ty, alloca, i
                    )
                    .unwrap();
                    writeln!(
                        self.output,
                        "  store {} {}, {}* {}",
                        field_ty, val, field_ty, gep
                    )
                    .unwrap();
                }
                alloca
            }
            Expr::FieldAccess { target, field } => {
                let target_val = self.gen_expr(target);
                // Get struct type from the variable directly if possible
                let struct_ty = if let Expr::Ident(name) = target.as_ref() {
                    if let Some((_, ty)) = self.variables.get(name) {
                        ty.clone()
                    } else {
                        self.infer_llvm_type(target)
                    }
                } else {
                    self.infer_llvm_type(target)
                };
                let fields_info = self.infer_struct_fields(target);
                if let Some(fields) = fields_info {
                    if let Some((idx, (_n, field_ty))) =
                        fields.iter().enumerate().find(|(_i, (n, _ty))| n == field)
                    {
                        let gep = self.fresh_var();
                        writeln!(
                            self.output,
                            "  {} = getelementptr {}, {}* {}, i32 0, i32 {}",
                            gep, struct_ty, struct_ty, target_val, idx
                        )
                        .unwrap();
                        let loaded = self.fresh_var();
                        writeln!(
                            self.output,
                            "  {} = load {}, {}* {}",
                            loaded, field_ty, field_ty, gep
                        )
                        .unwrap();
                        return loaded;
                    }
                }
                "0".to_string()
            }
            Expr::Lambda { params, ret, body } => {
                let lambda_name = format!("__lambda_{}", self.lambda_counter);
                self.lambda_counter += 1;
                self.pending_lambdas.push((
                    lambda_name.clone(),
                    params.clone(),
                    ret.clone(),
                    body.clone(),
                ));
                lambda_name
            }
            Expr::Range {
                start,
                end,
                inclusive,
            } => {
                let s = self.gen_expr(start);
                let e = self.gen_expr(end);
                let inc = if *inclusive { 1 } else { 0 };
                let result = self.fresh_var();
                writeln!(
                    self.output,
                    "  {} = call {{ i64, i64, i32 }} @sbx_range_create(i64 {}, i64 {}, i32 {})",
                    result, s, e, inc
                )
                .unwrap();
                result
            }
            Expr::FString(parts) => {
                // Build f-string via concatenated string literals in LLVM
                // For simplicity, fall back to a runtime call
                let mut concat_args = String::new();
                let mut count = 0i32;
                for part in parts {
                    match part {
                        crate::ast::FStringPart::Literal(s) => {
                            let name = self.fresh_str(s);
                            let len = s.len() + 1;
                            if count > 0 {
                                concat_args.push_str(", ");
                            }
                            concat_args.push_str(&format!(
                                "i8* bitcast ([{} x i8]* @{} to i8*)",
                                len, name
                            ));
                            count += 1;
                        }
                        crate::ast::FStringPart::Expr(expr) => {
                            let val = self.gen_expr(expr);
                            let ty = self.infer_llvm_type(expr);
                            // For i64 values, we need to convert to string at runtime
                            // For now, call __sbx_to_string
                            if ty == "i64" {
                                let str_val = self.fresh_var();
                                writeln!(
                                    self.output,
                                    "  {} = call i8* @__sbx_to_string(i64 {})",
                                    str_val, val
                                )
                                .unwrap();
                                if count > 0 {
                                    concat_args.push_str(", ");
                                }
                                concat_args.push_str(&format!("i8* {}", str_val));
                            } else {
                                if count > 0 {
                                    concat_args.push_str(", ");
                                }
                                concat_args.push_str(&format!("i8* {}", val));
                            }
                            count += 1;
                        }
                    }
                }
                let result = self.fresh_var();
                writeln!(
                    self.output,
                    "  {} = call i8* @__sbx_str_concat_multi(i32 {}, {})",
                    result, count, concat_args
                )
                .unwrap();
                result
            }
            _ => "0".to_string(),
        }
    }

    /// Given an expression that yields a struct, return its field definitions
    fn infer_struct_fields(&self, expr: &Expr) -> Option<Vec<(String, String)>> {
        match expr {
            Expr::Ident(name) => {
                if let Some((_, ty)) = self.variables.get(name) {
                    if let Some(struct_name) = ty.strip_prefix('%') {
                        return self.struct_defs.get(struct_name).cloned();
                    }
                }
                None
            }
            Expr::FieldAccess { target, field, .. } => {
                if let Some(fields) = self.infer_struct_fields(target) {
                    if let Some((_n, field_ty)) = fields.iter().find(|(n, _)| n == field) {
                        if let Some(struct_name) = field_ty.strip_prefix('%') {
                            return self.struct_defs.get(struct_name).cloned();
                        }
                    }
                }
                None
            }
            Expr::StructLiteral { name, .. } => self.struct_defs.get(name).cloned(),
            _ => None,
        }
    }

    fn gen_print_call(&mut self, val: &str, ty: &str) {
        match ty {
            "i64" => {
                let fmt = self.fresh_str("%ld\n");
                let len = 5;
                writeln!(
                    self.output,
                    "  call i64 (i8*, ...) @printf(i8* bitcast ([{} x i8]* @{} to i8*), i64 {})",
                    len, fmt, val
                )
                .unwrap();
            }
            "double" => {
                let fmt = self.fresh_str("%f\n");
                let len = 4;
                writeln!(
                    self.output,
                    "  call i64 (i8*, ...) @printf(i8* bitcast ([{} x i8]* @{} to i8*), double {})",
                    len, fmt, val
                )
                .unwrap();
            }
            "i8*" => {
                let fmt = self.fresh_str("%s\n");
                let len = 4;
                writeln!(
                    self.output,
                    "  call i64 (i8*, ...) @printf(i8* bitcast ([{} x i8]* @{} to i8*), i8* {})",
                    len, fmt, val
                )
                .unwrap();
            }
            "i1" => {
                let fmt = self.fresh_str("%d\n");
                let len = 4;
                writeln!(
                    self.output,
                    "  call i64 (i8*, ...) @printf(i8* bitcast ([{} x i8]* @{} to i8*), i1 {})",
                    len, fmt, val
                )
                .unwrap();
            }
            _ => {
                let fmt = self.fresh_str("%ld\n");
                let len = 5;
                writeln!(
                    self.output,
                    "  call i64 (i8*, ...) @printf(i8* bitcast ([{} x i8]* @{} to i8*), i64 {})",
                    len, fmt, val
                )
                .unwrap();
            }
        }
    }

    fn llvm_type(&self, ty: &Type) -> String {
        match ty {
            Type::I64 => "i64".to_string(),
            Type::F64 => "double".to_string(),
            Type::Bool => "i1".to_string(),
            Type::String => "i8*".to_string(),
            Type::Void => "void".to_string(),
            Type::Money(_) | Type::Decimal | Type::Unit(_) => "i64".to_string(),
            Type::Array(_) => "i8*".to_string(),
            Type::Custom(name) => {
                if self.enum_tags.contains_key(name) {
                    "i64".to_string()
                } else if self.struct_defs.contains_key(name) {
                    format!("%{}", name)
                } else {
                    "%".to_string() + name
                }
            }
            Type::Result(_, _) => "i64".to_string(),
            Type::Fn(params, ret) => {
                let params_str: Vec<String> = params.iter().map(|p| self.llvm_type(p)).collect();
                format!("{} ({})", self.llvm_type(ret), params_str.join(", "))
            }
        }
    }

    fn infer_llvm_type(&self, expr: &Expr) -> String {
        match expr {
            Expr::Int(_) => "i64".to_string(),
            Expr::Float(_) => "double".to_string(),
            Expr::Bool(_) => "i1".to_string(),
            Expr::Str(_) => "i8*".to_string(),
            Expr::EnumVariant { .. } => "i64".to_string(),
            Expr::Match { .. } => "i64".to_string(),
            Expr::Call { name, .. } => {
                if let Some((_, ret)) = self.fn_sigs.get(name) {
                    ret.clone()
                } else {
                    "i64".to_string()
                }
            }
            Expr::Ident(name) => {
                if let Some((_, ty)) = self.variables.get(name) {
                    ty.clone()
                } else {
                    "i64".to_string()
                }
            }
            Expr::BinaryOp {
                op:
                    BinOp::Eq
                    | BinOp::Neq
                    | BinOp::Lt
                    | BinOp::Gt
                    | BinOp::Le
                    | BinOp::Ge
                    | BinOp::And
                    | BinOp::Or,
                ..
            } => "i1".to_string(),
            Expr::BinaryOp { .. } => "i64".to_string(),
            Expr::StructLiteral { name, .. } => format!("%{}", name),
            Expr::FieldAccess { target, field, .. } => {
                if let Some(fields) = self.infer_struct_fields(target) {
                    if let Some((_, field_ty)) = fields.iter().find(|(n, _)| n == field) {
                        return field_ty.clone();
                    }
                }
                "i64".to_string()
            }
            Expr::Range { .. } => "i64".to_string(),
            Expr::FString(_) => "i8*".to_string(),
            _ => "i64".to_string(),
        }
    }

    fn fresh_var(&mut self) -> String {
        let v = format!("%v{}", self.var_counter);
        self.var_counter += 1;
        v
    }

    fn fresh_label(&mut self, prefix: &str) -> String {
        let l = format!("{}_{}", prefix, self.var_counter);
        self.var_counter += 1;
        l
    }

    fn fresh_str(&mut self, content: &str) -> String {
        let name = format!(".str.{}", self.strings.len());
        self.strings.push((name.clone(), content.to_string()));
        name
    }
}
