use crate::ast::*;
use std::fmt::Write;

/// WebAssembly text format code generator
pub struct WasmGen {
    output: String,
    indent: usize,
    func_count: u32,
    string_data: Vec<(u32, String)>,
    string_offsets: Vec<u32>,
    memory_size: u32,
    /// Total string bytes laid out by collect_strings (data segment end).
    data_end: u32,
    /// Counter for unique hidden temp locals (array construction).
    temp_count: u32,
    /// Hidden temps created while generating the current function; they
    /// become extra i64 locals in that function's declaration list.
    extra_locals: Vec<String>,
    /// Variables currently bound to heap arrays in the function being
    /// generated (locals are function-scoped; b2's block-scoping pass has
    /// already renamed shadowing bindings, so names are unique per fn).
    array_vars: std::collections::HashSet<String>,
}

impl WasmGen {
    pub fn new() -> Self {
        Self {
            output: String::new(),
            indent: 0,
            func_count: 0,
            string_data: Vec::new(),
            string_offsets: Vec::new(),
            memory_size: 1, // start with 1 page (64KB)
            data_end: 0,
            temp_count: 0,
            extra_locals: Vec::new(),
            array_vars: std::collections::HashSet::new(),
        }
    }

    pub fn generate(&mut self, program: &Program) -> String {
        // Collect string literals first
        self.collect_strings(program);

        // Arrays bump-allocate on the heap: the $heap global starts just
        // past the string data (arrays are 8-byte aligned, so pad the
        // offset up). Size memory to fit the sum of literal data plus a
        // generous scratch pad for runtime allocation.
        let heap_start = (self.data_end + 7) & !7u32;
        let used_bytes = heap_start + 4096; // strings + heap start slot + 4KB scratch
        let pages_needed = used_bytes.div_ceil(65536).max(1);
        if pages_needed > self.memory_size {
            self.memory_size = pages_needed;
        }

        writeln!(self.output, ";; Generated by Sandbox v0.4.0").unwrap();
        writeln!(self.output, ";; WebAssembly Text Format (.wat)").unwrap();
        writeln!(self.output).unwrap();

        // Memory declaration
        writeln!(self.output, "(module").unwrap();
        self.indent += 1;

        // Import console.log for print
        self.write_indent();
        writeln!(
            self.output,
            "(import \"console\" \"log\" (func $log (param i64)))"
        )
        .unwrap();

        // Memory
        self.write_indent();
        writeln!(
            self.output,
            "(memory (export \"memory\") {})",
            self.memory_size
        )
        .unwrap();

        // String data section
        if !self.string_data.is_empty() {
            self.write_indent();
            writeln!(self.output, "(data (i32.const 0)").unwrap();
            self.indent += 1;
            for (_, s) in self.string_data.clone() {
                self.write_indent();
                let escaped = s
                    .replace('\\', "\\\\")
                    .replace('"', "\\\"")
                    .replace('\n', "\\0a");
                // Bare string literal — standard WAT data segments do not
                // parenthesize individual strings (wat2wasm rejects that).
                writeln!(self.output, "\"{}\"", escaped).unwrap();
            }
            self.indent -= 1;
            self.write_indent();
            writeln!(self.output, ")").unwrap();
        }

        // Runtime helpers for heap arrays — emitted BEFORE user functions
        // so calls from anywhere resolve (text order is irrelevant for
        // validation but matters for readability of generated WAT).
        self.emit_array_runtime(heap_start);

        writeln!(self.output).unwrap();

        // Generate functions
        for item in &program.items {
            match item {
                TopLevel::FnDef {
                    name,
                    params,
                    ret,
                    body,
                    ..
                } => {
                    self.gen_wasm_fn(name, params, ret, body);
                }
                TopLevel::ModuleDef { items, .. } => {
                    for item in items {
                        if let TopLevel::FnDef {
                            name,
                            params,
                            ret,
                            body,
                            ..
                        } = item
                        {
                            self.gen_wasm_fn(name, params, ret, body);
                        }
                    }
                }
                _ => {}
            }
        }

        self.indent -= 1;
        writeln!(self.output, ")").unwrap();

        self.output.clone()
    }

    fn collect_strings(&mut self, program: &Program) {
        let mut offset: u32 = 0;
        self.collect_strings_from_items(&program.items, &mut offset);
        self.data_end = offset;
    }

    fn collect_strings_from_items(&mut self, items: &[TopLevel], offset: &mut u32) {
        for item in items {
            match item {
                TopLevel::FnDef { body, .. } => {
                    self.collect_strings_from_stmts(body, offset);
                }
                TopLevel::ModuleDef { items, .. } => {
                    self.collect_strings_from_items(items, offset);
                }
                _ => {}
            }
        }
    }

    fn collect_strings_from_stmts(&mut self, stmts: &[Stmt], offset: &mut u32) {
        for stmt in stmts {
            match stmt {
                Stmt::Let { value, .. } => {
                    self.collect_strings_from_expr(value, offset);
                }
                Stmt::Assign { value, .. } => {
                    self.collect_strings_from_expr(value, offset);
                }
                Stmt::If {
                    condition,
                    then,
                    else_,
                } => {
                    self.collect_strings_from_expr(condition, offset);
                    self.collect_strings_from_stmts(then, offset);
                    if let Some(else_body) = else_ {
                        self.collect_strings_from_stmts(else_body, offset);
                    }
                }
                Stmt::While { condition, body } => {
                    self.collect_strings_from_expr(condition, offset);
                    self.collect_strings_from_stmts(body, offset);
                }
                Stmt::For { iterable, body, .. } => {
                    self.collect_strings_from_expr(iterable, offset);
                    self.collect_strings_from_stmts(body, offset);
                }
                Stmt::Return(Some(expr)) => {
                    self.collect_strings_from_expr(expr, offset);
                }
                Stmt::Print(expr) => {
                    self.collect_strings_from_expr(expr, offset);
                }
                Stmt::ExprStmt(expr) => {
                    self.collect_strings_from_expr(expr, offset);
                }
                _ => {}
            }
        }
    }

    fn collect_strings_from_expr(&mut self, expr: &Expr, offset: &mut u32) {
        match expr {
            Expr::Str(s) => {
                let len = s.len() as u32;
                self.string_data.push((*offset, s.clone()));
                self.string_offsets.push(*offset);
                *offset += len + 1; // +1 for null terminator
            }
            Expr::BinaryOp { left, right, .. } => {
                self.collect_strings_from_expr(left, offset);
                self.collect_strings_from_expr(right, offset);
            }
            Expr::UnaryOp { expr, .. } => {
                self.collect_strings_from_expr(expr, offset);
            }
            Expr::Call { args, .. } => {
                for arg in args {
                    self.collect_strings_from_expr(arg, offset);
                }
            }
            Expr::Index { target, index } => {
                self.collect_strings_from_expr(target, offset);
                self.collect_strings_from_expr(index, offset);
            }
            Expr::FieldAccess { target, .. } => {
                self.collect_strings_from_expr(target, offset);
            }
            Expr::ArrayLiteral(elems) => {
                for e in elems {
                    self.collect_strings_from_expr(e, offset);
                }
            }
            Expr::OkExpr(e) | Expr::ErrExpr(e) | Expr::PanicExpr(e) | Expr::TryExpr(e) => {
                self.collect_strings_from_expr(e, offset);
            }
            _ => {}
        }
    }

    /// Emit construction of a heap array bound to the wasm local
    /// `wat_name` (including its leading '$') from an ArrayLiteral:
    /// allocate the storage ($sbx_arr_new), then store each element through
    /// $sbx_store so element expressions can't clobber the array local
    /// before construction completes.
    fn gen_array_literal(&mut self, wat_name: &str, elems: &[Expr]) {
        self.write_indent();
        writeln!(self.output, "(local.set {}", wat_name).unwrap();
        self.indent += 1;
        self.write_indent();
        writeln!(
            self.output,
            "(call $sbx_arr_new (i64.const {}))",
            elems.len()
        )
        .unwrap();
        self.indent -= 1;
        self.write_indent();
        writeln!(self.output, ")").unwrap();
        for (i, e) in elems.iter().enumerate() {
            self.write_indent();
            writeln!(
                self.output,
                "(call $sbx_store (local.get {}) (i64.const {}) ",
                wat_name, i
            )
            .unwrap();
            self.gen_wasm_expr(e);
            self.write_indent();
            writeln!(self.output, ")").unwrap();
            writeln!(self.output).unwrap();
        }
    }

    /// Build an anonymous heap array (call argument, print operand, nested
    /// position) into a fresh temp and leave its address on the stack.
    fn gen_anon_array(&mut self, elems: &[Expr]) -> String {
        let tmp = self.fresh_array_temp();
        self.gen_array_literal(&tmp, elems);
        self.write_indent();
        writeln!(self.output, "(local.get {})", tmp).unwrap();
        tmp
    }

    /// `for x in arr`: fresh index temp, loop while idx < $sbx_len(arr),
    /// re-seed x from $sbx_get at the top of each iteration. $break/$continue
    /// semantics match the range lowering (continue falls to the increment).
    /// `arr_wat` is the wasm name of the array local (leading '$').
    fn gen_for_over_array(&mut self, variable: &str, arr_wat: &str, body: &[Stmt]) {
        let idx = self.fresh_array_temp();
        self.write_indent();
        writeln!(self.output, "(local.set {} (i64.const 0))", idx).unwrap();

        self.write_indent();
        writeln!(self.output, "(block $break").unwrap();
        self.indent += 1;
        self.write_indent();
        writeln!(self.output, "(loop $top").unwrap();
        self.indent += 1;

        // br_if $break when !(idx < len(arr))
        self.write_indent();
        writeln!(self.output, "(br_if $break").unwrap();
        self.indent += 1;
        self.write_indent();
        writeln!(self.output, "(i32.eqz").unwrap();
        self.indent += 1;
        self.write_indent();
        writeln!(self.output, "(i64.lt_s").unwrap();
        self.indent += 1;
        self.write_indent();
        writeln!(self.output, "(local.get {})", idx).unwrap();
        self.write_indent();
        writeln!(self.output, "(call $sbx_len (local.get {}))", arr_wat).unwrap();
        self.indent -= 1;
        self.write_indent();
        writeln!(self.output, ")").unwrap();
        self.indent -= 1;
        self.write_indent();
        writeln!(self.output, ")").unwrap();
        self.indent -= 1;
        self.write_indent();
        writeln!(self.output, ")").unwrap();

        // Re-seed the binding from the array each iteration.
        self.write_indent();
        writeln!(self.output, "(local.set ${}", variable).unwrap();
        self.indent += 1;
        self.write_indent();
        writeln!(
            self.output,
            "(call $sbx_get (local.get {}) (local.get {}))",
            arr_wat, idx
        )
        .unwrap();
        self.indent -= 1;
        self.write_indent();
        writeln!(self.output, ")").unwrap();

        // Body inside a $continue block.
        self.write_indent();
        writeln!(self.output, "(block $continue").unwrap();
        self.indent += 1;
        for s in body {
            self.gen_wasm_stmt(s);
        }
        self.indent -= 1;
        self.write_indent();
        writeln!(self.output, ")").unwrap();

        // idx = idx + 1; br $top
        self.write_indent();
        writeln!(
            self.output,
            "(local.set {} (i64.add (local.get {}) (i64.const 1)))",
            idx, idx
        )
        .unwrap();
        self.write_indent();
        writeln!(self.output, "(br $top)").unwrap();
        self.indent -= 1;
        self.write_indent();
        writeln!(self.output, ")").unwrap();
        self.indent -= 1;
        self.write_indent();
        writeln!(self.output, ")").unwrap();
    }

    /// Allocate a unique hidden i64 temp local name (e.g. "$sbxtmp1").
    fn fresh_array_temp(&mut self) -> String {
        self.temp_count += 1;
        let name = format!("$sbxtmp{}", self.temp_count);
        if !self.extra_locals.contains(&name) {
            self.extra_locals.push(name.clone());
        }
        name
    }

    /// Emit the heap-array runtime: a bump-allocator global plus five
    /// helpers, all written in the same folded-WAT grammar the encoder
    /// already covers (generic folded opcodes + i32 arith, wrap, load/store
    /// with natural-alignment memargs, global.get/set).
    ///
    /// Array representation: the value stored in a user local is the
    /// address of an 8-byte length header followed by the packed i64
    /// elements — held as i64 like every other value (the i32 wrap happens
    /// inside the helpers, so call sites stay type-clean).
    ///
    ///   (global $heap (mut i32) (i32.const <heap_start>))
    ///   (func $sbx_alloc (param $n i32) (result i32)         ; bump n bytes
    ///   (func $sbx_arr_new (param $count i64) (result i64)   ; header+elems
    ///   (func $sbx_len (param $arr i64) (result i64)         ; header read
    ///   (func $sbx_get (param $arr i64) (param $idx i64) (result i64)
    ///   (func $sbx_store (param $arr i64) (param $idx i64) (param $v i64)
    ///
    /// Value-returning helpers end in an explicit (return ...) so the JS
    /// encoder's fall-through pin (which appends (unreachable) to result
    /// functions that fall off the end) never fires on them.
    fn emit_array_runtime(&mut self, heap_start: u32) {
        self.write_indent();
        writeln!(
            self.output,
            "(global $heap (mut i32) (i32.const {}))",
            heap_start
        )
        .unwrap();

        // $sbx_alloc(n:i32) -> i32: old = heap; heap += n; return old.
        self.write_indent();
        writeln!(self.output, "(func $sbx_alloc (param $n i32) (result i32)").unwrap();
        self.indent += 1;
        self.write_indent();
        writeln!(self.output, "(local $old i32)").unwrap();
        self.write_indent();
        writeln!(self.output, "(local.set $old (global.get $heap))").unwrap();
        self.write_indent();
        writeln!(
            self.output,
            "(global.set $heap (i32.add (global.get $heap) (local.get $n)))"
        )
        .unwrap();
        self.write_indent();
        writeln!(self.output, "(return (local.get $old))").unwrap();
        self.indent -= 1;
        self.write_indent();
        writeln!(self.output, ")").unwrap();

        // $sbx_arr_new(count:i64) -> i64: allocate 8 + 8*count bytes and
        // store the count into the header.
        self.write_indent();
        writeln!(
            self.output,
            "(func $sbx_arr_new (param $count i64) (result i64)"
        )
        .unwrap();
        self.indent += 1;
        self.write_indent();
        writeln!(self.output, "(local $arr i32)").unwrap();
        self.write_indent();
        writeln!(
            self.output,
            "(local.set $arr (call $sbx_alloc (i32.add (i32.const 8) (i32.wrap_i64 (i64.mul (local.get $count) (i64.const 8))))))"
        )
        .unwrap();
        self.write_indent();
        writeln!(
            self.output,
            "(i64.store (local.get $arr) (local.get $count))"
        )
        .unwrap();
        self.write_indent();
        writeln!(self.output, "(return (i64.extend_i32_u (local.get $arr)))").unwrap();
        self.indent -= 1;
        self.write_indent();
        writeln!(self.output, ")").unwrap();

        // $sbx_len(arr) -> i64: read the header.
        self.write_indent();
        writeln!(self.output, "(func $sbx_len (param $arr i64) (result i64)").unwrap();
        self.indent += 1;
        self.write_indent();
        writeln!(
            self.output,
            "(return (i64.load (i32.wrap_i64 (local.get $arr))))"
        )
        .unwrap();
        self.indent -= 1;
        self.write_indent();
        writeln!(self.output, ")").unwrap();

        // $sbx_get(arr, idx) -> i64: load arr + 8 + idx*8.
        self.write_indent();
        writeln!(
            self.output,
            "(func $sbx_get (param $arr i64) (param $idx i64) (result i64)"
        )
        .unwrap();
        self.indent += 1;
        self.write_indent();
        writeln!(
            self.output,
            "(return (i64.load (i32.add (i32.wrap_i64 (local.get $arr)) (i32.wrap_i64 (i64.add (i64.mul (local.get $idx) (i64.const 8)) (i64.const 8))))))"
        )
        .unwrap();
        self.indent -= 1;
        self.write_indent();
        writeln!(self.output, ")").unwrap();

        // $sbx_store(arr, idx, v): store v at arr + 8 + idx*8. Returns
        // nothing, so a plain (no-return) tail is correct here.
        self.write_indent();
        writeln!(
            self.output,
            "(func $sbx_store (param $arr i64) (param $idx i64) (param $v i64)"
        )
        .unwrap();
        self.indent += 1;
        self.write_indent();
        writeln!(
            self.output,
            "(i64.store (i32.add (i32.wrap_i64 (local.get $arr)) (i32.wrap_i64 (i64.add (i64.mul (local.get $idx) (i64.const 8)) (i64.const 8)))) (local.get $v))"
        )
        .unwrap();
        self.indent -= 1;
        self.write_indent();
        writeln!(self.output, ")").unwrap();
        writeln!(self.output).unwrap();
    }

    fn gen_wasm_fn(&mut self, name: &str, params: &[Param], ret: &Option<Type>, body: &[Stmt]) {
        self.func_count += 1;
        self.array_vars.clear();
        // Array-typed parameters hold a heap address (an i64) exactly like a
        // local array binding — register them so t[i], len(t) and for-in
        // lower through the array runtime.
        for p in params {
            if matches!(p.ty, Type::Array(_)) {
                self.array_vars.insert(p.name.clone());
            }
        }

        // Function signature
        self.write_indent();
        write!(self.output, "(func ${}", name).unwrap();

        // Parameters
        for p in params {
            write!(self.output, " (param ${} i64)", p.name).unwrap();
        }

        // Return type
        if ret.is_some() {
            write!(self.output, " (result i64)").unwrap();
        }

        writeln!(self.output).unwrap();
        self.indent += 1;

        // Local variables: params are already declared; then declare every
        // let/assign-bound name (collected recursively so nested if/while
        // bodies get theirs too).
        let mut locals: Vec<String> = params.iter().map(|p| p.name.clone()).collect();
        Self::collect_locals(body, &mut locals);
        for name in &locals[params.len()..] {
            self.write_indent();
            writeln!(self.output, "(local ${} i64)", name).unwrap();
        }

        // Function body — generated first, then hidden temps discovered
        // during codegen (array construction) are spliced in as extra
        // i64 local declarations before the instructions. Their names
        // embed a '$' (e.g. "$sbxtmp1"), which source identifiers cannot
        // contain, so they can never collide with a user local.
        let body_start = self.output.len();
        for stmt in body {
            self.gen_wasm_stmt(stmt);
        }
        let body_text = self.output.split_off(body_start);
        for name in std::mem::take(&mut self.extra_locals) {
            self.write_indent();
            writeln!(self.output, "(local {} i64)", name).unwrap();
        }
        self.output.push_str(&body_text);

        // A function with a result must deliver it on every path to the end.
        // Bodies whose control flow ends without a trailing (return) — e.g. a
        // value-yielding `if` whose branches both return — still reach the
        // end in reachable validation state, so pin the end with (unreachable):
        // it is dead code on real paths and traps on impossible fall-through.
        if ret.is_some() && !ends_with_return(body) {
            self.write_indent();
            writeln!(self.output, "(unreachable)").unwrap();
        }

        self.indent -= 1;
        self.write_indent();
        writeln!(self.output, ")").unwrap();

        // Export main
        if name == "main" {
            self.write_indent();
            writeln!(self.output, "(export \"main\" (func $main))").unwrap();
        }

        writeln!(self.output).unwrap();
    }

    /// Collect the names bound by `let`/`assign` statements (recursively
    /// through if/while/for bodies) so they can be declared as wasm locals.
    /// Named wasm locals are function-scoped, so shadowing declarations fold
    /// into one local with assignment semantics.
    fn collect_locals(stmts: &[Stmt], locals: &mut Vec<String>) {
        for stmt in stmts {
            match stmt {
                Stmt::Let { name, .. } | Stmt::Assign { name, .. } => {
                    if !locals.contains(name) {
                        locals.push(name.clone());
                    }
                }
                Stmt::If { then, else_, .. } => {
                    Self::collect_locals(then, locals);
                    if let Some(else_body) = else_ {
                        Self::collect_locals(else_body, locals);
                    }
                }
                Stmt::IfLet { then, else_, .. } => {
                    Self::collect_locals(then, locals);
                    if let Some(else_body) = else_ {
                        Self::collect_locals(else_body, locals);
                    }
                }
                Stmt::While { body, .. } => Self::collect_locals(body, locals),
                Stmt::For { variable, body, .. } => {
                    if !locals.contains(variable) {
                        locals.push(variable.clone());
                    }
                    Self::collect_locals(body, locals);
                }
                _ => {}
            }
        }
    }

    fn gen_wasm_stmt(&mut self, stmt: &Stmt) {
        match stmt {
            Stmt::Let { name, value, .. } => {
                // Heap arrays: build with $sbx_arr_new + element stores.
                if let Expr::ArrayLiteral(elems) = value {
                    self.gen_array_literal(&format!("${}", name), elems);
                    self.array_vars.insert(name.clone());
                    return;
                }
                // Aliasing: `let b = a` copies the array address — b is an
                // array reference too (shared storage, like all backends).
                if let Expr::Ident(src) = value {
                    if self.array_vars.contains(src) {
                        self.array_vars.insert(name.clone());
                    }
                }
                self.write_indent();
                writeln!(self.output, "(local.set ${}", name).unwrap();
                self.indent += 1;
                self.gen_wasm_expr(value);
                self.indent -= 1;
                self.write_indent();
                writeln!(self.output, ")").unwrap();
            }
            Stmt::Assign { name, value } => {
                if let Expr::ArrayLiteral(elems) = value {
                    self.gen_array_literal(&format!("${}", name), elems);
                    self.array_vars.insert(name.clone());
                    return;
                }
                if let Expr::Ident(src) = value {
                    if self.array_vars.contains(src) {
                        self.array_vars.insert(name.clone());
                    }
                }
                self.write_indent();
                writeln!(self.output, "(local.set ${}", name).unwrap();
                self.indent += 1;
                self.gen_wasm_expr(value);
                self.indent -= 1;
                self.write_indent();
                writeln!(self.output, ")").unwrap();
            }
            Stmt::If {
                condition,
                then,
                else_,
            } => {
                self.write_indent();
                writeln!(self.output, "(if").unwrap();
                self.indent += 1;
                // Condition
                self.gen_wasm_cond(condition);
                self.write_indent();
                writeln!(self.output, "(then").unwrap();
                self.indent += 1;
                for s in then {
                    self.gen_wasm_stmt(s);
                }
                self.indent -= 1;
                self.write_indent();
                writeln!(self.output, ")").unwrap();
                if let Some(else_body) = else_ {
                    self.write_indent();
                    writeln!(self.output, "(else").unwrap();
                    self.indent += 1;
                    for s in else_body {
                        self.gen_wasm_stmt(s);
                    }
                    self.indent -= 1;
                    self.write_indent();
                    writeln!(self.output, ")").unwrap();
                }
                self.indent -= 1;
                self.write_indent();
                writeln!(self.output, ")").unwrap();
            }
            Stmt::While { condition, body } => {
                self.write_indent();
                writeln!(self.output, "(block $break").unwrap();
                self.indent += 1;
                self.write_indent();
                writeln!(self.output, "(loop $continue").unwrap();
                self.indent += 1;

                // Condition check — gen_wasm_cond yields i32; invert it
                // for br_if (break when the condition is false).
                self.write_indent();
                writeln!(self.output, "(br_if $break").unwrap();
                self.indent += 1;
                self.write_indent();
                writeln!(self.output, "(i32.eqz").unwrap();
                self.indent += 1;
                self.gen_wasm_cond(condition);
                self.indent -= 1;
                self.write_indent();
                writeln!(self.output, ")").unwrap();
                self.indent -= 1;
                self.write_indent();
                writeln!(self.output, ")").unwrap();

                // Body
                for s in body {
                    self.gen_wasm_stmt(s);
                }

                // Loop back
                self.write_indent();
                writeln!(self.output, "(br $continue)").unwrap();

                self.indent -= 1;
                self.write_indent();
                writeln!(self.output, ")").unwrap();
                self.indent -= 1;
                self.write_indent();
                writeln!(self.output, ")").unwrap();
            }
            Stmt::For {
                variable,
                iterable,
                body,
            } => {
                // Range iteration is lowered to a while-style loop with the
                // increment outside the continue-target block, so `continue`
                // still advances the counter. Heap-array iteration re-seeds
                // the binding from the array each iteration (all backends
                // agree on that semantics); string iteration remains an
                // unsupported no-op (documented parity gap).
                if let Expr::Range {
                    start,
                    end,
                    inclusive,
                } = iterable
                {
                    // i = start
                    self.write_indent();
                    writeln!(self.output, "(local.set ${}", variable).unwrap();
                    self.indent += 1;
                    self.gen_wasm_expr(start);
                    self.indent -= 1;
                    self.write_indent();
                    writeln!(self.output, ")").unwrap();

                    self.write_indent();
                    writeln!(self.output, "(block $break").unwrap();
                    self.indent += 1;
                    self.write_indent();
                    writeln!(self.output, "(loop $top").unwrap();
                    self.indent += 1;

                    // br_if $break when !(i < end) (or !(i <= end) inclusive)
                    self.write_indent();
                    writeln!(self.output, "(br_if $break").unwrap();
                    self.indent += 1;
                    self.write_indent();
                    writeln!(self.output, "(i32.eqz").unwrap();
                    self.indent += 1;
                    self.write_indent();
                    if *inclusive {
                        writeln!(self.output, "(i64.le_s").unwrap();
                    } else {
                        writeln!(self.output, "(i64.lt_s").unwrap();
                    }
                    self.indent += 1;
                    self.write_indent();
                    writeln!(self.output, "(local.get ${})", variable).unwrap();
                    self.gen_wasm_expr(end);
                    self.indent -= 1;
                    self.write_indent();
                    writeln!(self.output, ")").unwrap();
                    self.indent -= 1;
                    self.write_indent();
                    writeln!(self.output, ")").unwrap();
                    self.indent -= 1;
                    self.write_indent();
                    writeln!(self.output, ")").unwrap();

                    // body inside a $continue block: `continue` exits here,
                    // falling through to the increment.
                    self.write_indent();
                    writeln!(self.output, "(block $continue").unwrap();
                    self.indent += 1;
                    for s in body {
                        self.gen_wasm_stmt(s);
                    }
                    self.indent -= 1;
                    self.write_indent();
                    writeln!(self.output, ")").unwrap();

                    // i = i + 1; br $top
                    self.write_indent();
                    writeln!(self.output, "(local.set ${}", variable).unwrap();
                    self.indent += 1;
                    self.write_indent();
                    writeln!(self.output, "(i64.add").unwrap();
                    self.indent += 1;
                    self.write_indent();
                    writeln!(self.output, "(local.get ${})", variable).unwrap();
                    self.write_indent();
                    writeln!(self.output, "(i64.const 1)").unwrap();
                    self.indent -= 1;
                    self.write_indent();
                    writeln!(self.output, ")").unwrap();
                    self.indent -= 1;
                    self.write_indent();
                    writeln!(self.output, ")").unwrap();

                    self.write_indent();
                    writeln!(self.output, "(br $top)").unwrap();
                    self.indent -= 1;
                    self.write_indent();
                    writeln!(self.output, ")").unwrap();
                    self.indent -= 1;
                    self.write_indent();
                    writeln!(self.output, ")").unwrap();
                    return;
                }
                // Heap-array iteration: `for x in arr` desugars to an index
                // loop. The binding is re-seeded from the array at the top
                // of each iteration, so a body assignment to `x` cannot
                // affect iteration (matching every backend).
                if let Expr::Ident(arr_name) = iterable {
                    if self.array_vars.contains(arr_name) {
                        self.gen_for_over_array(variable, &format!("${}", arr_name), body);
                        return;
                    }
                }
                // `for x in [1, 2, 3]`: construct the literal once into a
                // temp outside the loop, then iterate the temp.
                if let Expr::ArrayLiteral(elems) = iterable {
                    let tmp = self.fresh_array_temp();
                    self.gen_array_literal(&tmp, elems);
                    self.gen_for_over_array(variable, &tmp, body);
                }
            }
            Stmt::Break => {
                self.write_indent();
                writeln!(self.output, "(br $break)").unwrap();
            }
            Stmt::Continue => {
                self.write_indent();
                writeln!(self.output, "(br $continue)").unwrap();
            }
            Stmt::Return(Some(expr)) => {
                self.write_indent();
                self.gen_wasm_expr(expr);
                self.write_indent();
                writeln!(self.output, "(return)").unwrap();
            }
            Stmt::Return(None) => {
                self.write_indent();
                writeln!(self.output, "(nop)").unwrap();
            }
            Stmt::Print(expr) => {
                self.write_indent();
                writeln!(self.output, "(call $log").unwrap();
                self.indent += 1;
                self.gen_wasm_expr(expr);
                self.indent -= 1;
                self.write_indent();
                writeln!(self.output, ")").unwrap();
            }
            Stmt::ExprStmt(expr) => {
                // Statement-position expression: its value is discarded here.
                // (C treats a function's *last* ExprStmt as an implicit return;
                // that rule is applied uniformly in the compiler front-end, not
                // per-backend, so wasmgen never sees one in return position.)
                self.write_indent();
                writeln!(self.output, "(drop").unwrap();
                self.indent += 1;
                self.gen_wasm_expr(expr);
                self.indent -= 1;
                self.write_indent();
                writeln!(self.output, ")").unwrap();
            }
            Stmt::IfLet { .. } => {
                // Simplified: skip for WASM backend
            }
        }
    }

    /// Emit the i64 source of a cast, truncating float literals first.
    /// Handles `Float` and `-Float` (post-cast-precedence the desugar can
    /// produce); any other shape is already an i64-valued expression.
    fn gen_wasm_cast_source(&mut self, expr: &Expr) {
        let negate;
        let inner = match expr {
            Expr::Float(n) => {
                negate = false;
                *n
            }
            Expr::UnaryOp {
                op: UnOp::Neg,
                expr: inner,
            } => match inner.as_ref() {
                Expr::Float(n) => {
                    negate = true;
                    *n
                }
                _ => {
                    self.gen_wasm_expr(expr);
                    return;
                }
            },
            _ => {
                self.gen_wasm_expr(expr);
                return;
            }
        };
        let value = if negate { -inner } else { inner };
        self.write_indent();
        writeln!(self.output, "(i64.trunc_f64_s").unwrap();
        self.indent += 1;
        self.write_indent();
        writeln!(self.output, "(f64.const {})", value).unwrap();
        self.indent -= 1;
        self.write_indent();
        writeln!(self.output, ")").unwrap();
    }

    /// Emit an i32 condition for if/while. Comparison operands produce i32
    /// directly; any other i64-valued expression is truth-tested with a
    /// non-zero compare.
    fn gen_wasm_cond(&mut self, expr: &Expr) {
        if let Expr::BinaryOp { op, left, right } = expr {
            if is_comparison(op) {
                let op_name = self.wasm_op(op).to_string();
                self.write_indent();
                writeln!(self.output, "(i64.{}", op_name).unwrap();
                self.indent += 1;
                self.gen_wasm_expr(left);
                self.gen_wasm_expr(right);
                self.indent -= 1;
                self.write_indent();
                writeln!(self.output, ")").unwrap();
                return;
            }
        }
        // Truthiness: non-zero means true.
        self.write_indent();
        writeln!(self.output, "(i64.ne").unwrap();
        self.indent += 1;
        self.gen_wasm_expr(expr);
        self.write_indent();
        writeln!(self.output, "(i64.const 0)").unwrap();
        self.indent -= 1;
        self.write_indent();
        writeln!(self.output, ")").unwrap();
    }

    fn gen_wasm_expr(&mut self, expr: &Expr) {
        match expr {
            Expr::Int(n) => {
                self.write_indent();
                writeln!(self.output, "(i64.const {})", n).unwrap();
            }
            Expr::Cast { expr, ty } => {
                // B2: mirror the i64-at-rest wrap. Float sources truncate
                // first (like the C backend's always-defined `(long long)`
                // two-step, truncation toward zero); everything else is
                // already i64. The wrap is fully nested folded WAT — flat
                // siblings inside a parent call/local.set parens would be
                // parsed as extra operands.
                match ty {
                    // Narrow int target: wrap. Any 64-bit or non-int target
                    // (e.g. legacy `Type::I64`) is an identity — the value is
                    // already a full i64 in wasm — but must still emit the
                    // source expression, or the operand stack is left empty.
                    Type::Int(t) if t.bits < 64 => {
                        let shift = 64 - t.bits as i64;
                        self.write_indent();
                        if t.signed {
                            writeln!(self.output, "(i64.shr_s").unwrap();
                        } else {
                            writeln!(self.output, "(i64.shr_u").unwrap();
                        }
                        self.indent += 1;
                        self.write_indent();
                        writeln!(self.output, "(i64.shl").unwrap();
                        self.indent += 1;
                        self.gen_wasm_cast_source(expr);
                        self.write_indent();
                        writeln!(self.output, "(i64.const {})", shift).unwrap();
                        self.indent -= 1;
                        self.write_indent();
                        writeln!(self.output, ")").unwrap();
                        self.write_indent();
                        writeln!(self.output, "(i64.const {})", shift).unwrap();
                        self.indent -= 1;
                        self.write_indent();
                        writeln!(self.output, ")").unwrap();
                    }
                    _ => self.gen_wasm_cast_source(expr),
                }
            }
            Expr::Float(n) => {
                // Wasm doesn't have f64 literals in WAT, use bit reinterpretation
                self.write_indent();
                writeln!(self.output, "(i64.reinterpret_f64 (f64.const {}))", n).unwrap();
            }
            Expr::Str(s) => {
                // Load string from memory
                if let Some(idx) = self.string_data.iter().position(|(_, data)| data == s) {
                    self.write_indent();
                    writeln!(self.output, "(i32.const {})", self.string_offsets[idx]).unwrap();
                } else {
                    self.write_indent();
                    writeln!(self.output, "(i32.const 0)").unwrap();
                }
            }
            Expr::Bool(b) => {
                self.write_indent();
                writeln!(self.output, "(i64.const {})", if *b { 1 } else { 0 }).unwrap();
            }
            Expr::Ident(name) => {
                self.write_indent();
                writeln!(self.output, "(local.get ${})", name).unwrap();
            }
            Expr::MoneyLiteral { amount, .. } => {
                let scaled = (*amount * 10000.0) as i64;
                self.write_indent();
                writeln!(self.output, "(i64.const {})", scaled).unwrap();
            }
            Expr::DecimalLiteral(s) => {
                if let Ok(val) = s.parse::<i64>() {
                    self.write_indent();
                    writeln!(
                        self.output,
                        "(i64.const {})",
                        val * 1_000_000_000_000_000_000i64
                    )
                    .unwrap();
                } else {
                    self.write_indent();
                    writeln!(self.output, "(i64.const 0)").unwrap();
                }
            }
            Expr::UnitLiteral { value, .. } => {
                self.gen_wasm_expr(value);
            }
            Expr::BinaryOp { op, left, right } => {
                let op_name = self.wasm_op(op).to_string();
                self.write_indent();
                writeln!(self.output, "(i64.{}", op_name).unwrap();
                self.indent += 1;
                self.gen_wasm_expr(left);
                self.gen_wasm_expr(right);
                self.indent -= 1;
                self.write_indent();
                writeln!(self.output, ")").unwrap();
                // Comparisons produce i32 in wasm; extend back to the i64
                // value representation so results are printable/storable.
                if is_comparison(op) {
                    self.write_indent();
                    writeln!(self.output, "(i64.extend_i32_u)").unwrap();
                }
            }
            Expr::UnaryOp { op, expr } => match op {
                UnOp::Neg => {
                    self.write_indent();
                    writeln!(self.output, "(i64.sub").unwrap();
                    self.indent += 1;
                    self.write_indent();
                    writeln!(self.output, "(i64.const 0)").unwrap();
                    self.gen_wasm_expr(expr);
                    self.indent -= 1;
                    self.write_indent();
                    writeln!(self.output, ")").unwrap();
                }
                UnOp::Not => {
                    // i64.eqz yields i32; value position needs i64, so
                    // zero-extend the boolean back up.
                    self.write_indent();
                    writeln!(self.output, "(i64.extend_i32_u").unwrap();
                    self.indent += 1;
                    self.write_indent();
                    writeln!(self.output, "(i64.eqz").unwrap();
                    self.indent += 1;
                    self.gen_wasm_expr(expr);
                    self.indent -= 1;
                    self.write_indent();
                    writeln!(self.output, ")").unwrap();
                    self.indent -= 1;
                    self.write_indent();
                    writeln!(self.output, ")").unwrap();
                }
                UnOp::BitNot => {
                    // ~x = x ^ -1
                    self.write_indent();
                    writeln!(self.output, "(i64.xor").unwrap();
                    self.indent += 1;
                    self.gen_wasm_expr(expr);
                    self.write_indent();
                    writeln!(self.output, "(i64.const -1)").unwrap();
                    self.indent -= 1;
                    self.write_indent();
                    writeln!(self.output, ")").unwrap();
                }
            },
            Expr::Index { target, index } => {
                // Heap-array element read: $sbx_get(arr, idx). The array is
                // held as i64, so no type gymnastics at the call site.
                if let Expr::Ident(arr_name) = target.as_ref() {
                    if self.array_vars.contains(arr_name) {
                        self.write_indent();
                        writeln!(self.output, "(call $sbx_get (local.get ${}) ", arr_name).unwrap();
                        self.gen_wasm_expr(index);
                        self.write_indent();
                        writeln!(self.output, ")").unwrap();
                        return;
                    }
                }
                self.write_indent();
                writeln!(self.output, "(i64.const 0) ;; TODO: {:?}", expr).unwrap();
            }
            Expr::ArrayLiteral(elems) => {
                // Array literal in a nested value position (call argument,
                // print operand, …): construct into a temp, yield address.
                self.gen_anon_array(elems);
            }
            Expr::Call {
                name,
                type_args: _,
                args,
            } => {
                // Builtin len(array): read the header via $sbx_len.
                if name == "len"
                    && args.len() == 1
                    && matches!(args[0], Expr::Ident(ref n) if self.array_vars.contains(n))
                {
                    if let Expr::Ident(arr_name) = &args[0] {
                        self.write_indent();
                        writeln!(self.output, "(call $sbx_len (local.get ${}))", arr_name).unwrap();
                        return;
                    }
                }
                self.write_indent();
                // Try to find function name with module prefix stripped
                let fn_name = name.rfind("::").map_or(name.as_str(), |i| &name[i + 2..]);
                writeln!(self.output, "(call ${}", fn_name).unwrap();
                self.indent += 1;
                for arg in args {
                    self.gen_wasm_expr(arg);
                }
                self.indent -= 1;
                self.write_indent();
                writeln!(self.output, ")").unwrap();
            }
            Expr::OkExpr(value) => {
                self.gen_wasm_expr(value);
            }
            Expr::ErrExpr(error) => {
                self.gen_wasm_expr(error);
            }
            Expr::PanicExpr(msg) => {
                self.write_indent();
                writeln!(self.output, "(call $log").unwrap();
                self.indent += 1;
                self.gen_wasm_expr(msg);
                self.indent -= 1;
                self.write_indent();
                writeln!(self.output, ")").unwrap();
                self.write_indent();
                writeln!(self.output, "(unreachable)").unwrap();
            }
            _ => {
                self.write_indent();
                writeln!(self.output, "(i64.const 0) ;; TODO: {:?}", expr).unwrap();
            }
        }
    }

    fn wasm_op(&self, op: &BinOp) -> &str {
        match op {
            BinOp::Add => "add",
            BinOp::Sub => "sub",
            BinOp::Mul => "mul",
            BinOp::Div => "div_s",
            BinOp::Mod => "rem_s",
            BinOp::Eq => "eq",
            BinOp::Neq => "ne",
            BinOp::Lt => "lt_s",
            BinOp::Gt => "gt_s",
            BinOp::Le => "le_s",
            BinOp::Ge => "ge_s",
            BinOp::And => "and",
            BinOp::Or => "or",
            // B1: bitwise (logical &&/|| were emitted as wasm and/or before
            // this — a pre-existing conflation, kept as-is here)
            BinOp::BitAnd => "and",
            BinOp::BitOr => "or",
            BinOp::BitXor => "xor",
            BinOp::Shl => "shl",
            BinOp::Shr => "shr_s",
        }
    }

    fn write_indent(&mut self) {
        for _ in 0..self.indent {
            write!(self.output, "  ").unwrap();
        }
    }
}

/// Does this statement list provably end in a `return` on every path?
/// Used to decide whether a result-producing function needs a trailing
/// `(unreachable)` to satisfy the wasm validator.
/// Does this statement list literally end in a `return`? Note an `if` whose
/// branches all return does NOT count: the if-instruction itself still
/// completes on the straight-line path, so the function end remains reachable
/// and needs `(unreachable)` under the validator.
fn ends_with_return(stmts: &[Stmt]) -> bool {
    matches!(stmts.last(), Some(Stmt::Return(_)))
}

/// Comparison operators: wasm emits these as i32-valued results, unlike the
/// arithmetic/bitwise ops which stay i64.
fn is_comparison(op: &BinOp) -> bool {
    matches!(
        op,
        BinOp::Eq | BinOp::Neq | BinOp::Lt | BinOp::Gt | BinOp::Le | BinOp::Ge
    )
}
